import { useEffect, useState } from 'react'
import { Accessibility, ArrowUp, Contrast, Eye, FileText, Link2, MousePointer2, Palette, RotateCcw, Type, X } from 'lucide-react'

const STORAGE_KEY='revtrove_accessibility'
const defaults={fontScale:1,grayscale:false,invert:false,lowSaturation:false,colorFilter:'none',contrast:false,bigText:false,highlightLinks:false,underlineLinks:false,hideImages:false,readableFont:false,lineSpacing:false,letterSpacing:false,alignLeft:false,bigCursor:false,reduceMotion:false,stopAnimations:false}
const labels={
  ar:{open:'فتح إمكانيات الوصول',top:'الصعود إلى الأعلى',title:'أدوات إمكانية الوصول',subtitle:'خصص تجربة استخدام الموقع حسب احتياجاتك',fontSize:'حجم النص',colorModes:'أوضاع الألوان',grayscale:'تدرج رمادي',invert:'عكس الألوان',lowSaturation:'ألوان منخفضة التشبع',colorFilter:'مرشح عمى الألوان',none:'بدون',redGreen:'أحمر–أخضر',blueYellow:'أزرق–أصفر',red:'أحمر',visual:'خيارات العرض',contrast:'تباين عالٍ',bigText:'نص كبير',highlightLinks:'إبراز الروابط',underlineLinks:'تسطير الروابط',hideImages:'إخفاء الصور',text:'خيارات النص',readableFont:'خط واضح',lineSpacing:'زيادة تباعد الأسطر',letterSpacing:'زيادة تباعد الحروف',alignLeft:'محاذاة النص لليسار',navigation:'خيارات التصفح',bigCursor:'مؤشر كبير',reduceMotion:'تقليل الحركة',stopAnimations:'إيقاف الرسوم المتحركة',reset:'إعادة الإعدادات الافتراضية',close:'إغلاق'},
  en:{open:'Open accessibility',top:'Scroll to top',title:'Accessibility tools',subtitle:'Customize the website experience to your needs',fontSize:'Text size',colorModes:'Color modes',grayscale:'Grayscale',invert:'Invert colors',lowSaturation:'Low saturation',colorFilter:'Color blindness filter',none:'None',redGreen:'Red–green',blueYellow:'Blue–yellow',red:'Red',visual:'Visual options',contrast:'High contrast',bigText:'Large text',highlightLinks:'Highlight links',underlineLinks:'Underline links',hideImages:'Hide images',text:'Text options',readableFont:'Readable font',lineSpacing:'Increase line spacing',letterSpacing:'Increase letter spacing',alignLeft:'Align text left',navigation:'Navigation options',bigCursor:'Large cursor',reduceMotion:'Reduce motion',stopAnimations:'Stop animations',reset:'Reset to defaults',close:'Close'},
  he:{open:'פתיחת אפשרויות נגישות',top:'חזרה לראש הדף',title:'כלי נגישות',subtitle:'התאימו את חוויית השימוש לצרכים שלכם',fontSize:'גודל טקסט',colorModes:'מצבי צבע',grayscale:'גווני אפור',invert:'היפוך צבעים',lowSaturation:'רוויה נמוכה',colorFilter:'מסנן עיוורון צבעים',none:'ללא',redGreen:'אדום–ירוק',blueYellow:'כחול–צהוב',red:'אדום',visual:'אפשרויות חזותיות',contrast:'ניגודיות גבוהה',bigText:'טקסט גדול',highlightLinks:'הדגשת קישורים',underlineLinks:'קו תחתון לקישורים',hideImages:'הסתרת תמונות',text:'אפשרויות טקסט',readableFont:'גופן קריא',lineSpacing:'הגדלת רווח בין שורות',letterSpacing:'רווח בין אותיות',alignLeft:'יישור טקסט לשמאל',navigation:'אפשרויות ניווט',bigCursor:'סמן גדול',reduceMotion:'הפחתת תנועה',stopAnimations:'עצירת אנימציות',reset:'איפוס לברירת מחדל',close:'סגירה'},
}

function loadSettings(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE_KEY))}}catch{return defaults}}
function pageFilter(settings){const values=[];if(settings.grayscale)values.push('grayscale(1)');if(settings.invert)values.push('invert(1) hue-rotate(180deg)');if(settings.lowSaturation)values.push('saturate(.35)');if(settings.colorFilter==='red')values.push('sepia(.3) saturate(1.45) hue-rotate(-18deg)');if(settings.colorFilter==='blueYellow')values.push('sepia(.25) saturate(1.25) hue-rotate(155deg)');if(settings.colorFilter==='redGreen')values.push('sepia(.35) saturate(.8) hue-rotate(25deg)');return values.join(' ')||'none'}
function applySettings(settings){const html=document.documentElement,filter=pageFilter(settings),scale=Math.min(1.7,Math.max(.85,settings.fontScale*(settings.bigText?1.18:1)));html.style.setProperty('--font-scale',scale.toFixed(2));html.style.setProperty('--a11y-page-filter',filter);html.classList.toggle('a11y-filtered',filter!=='none');['contrast','highlightLinks','underlineLinks','hideImages','readableFont','lineSpacing','letterSpacing','alignLeft','bigCursor','reduceMotion','stopAnimations'].forEach((key)=>html.classList.toggle(`a11y-${key}`,!!settings[key]))}

export default function AccessibilityTools({language='ar'}){
  const text=labels[language]||labels.en
  const [open,setOpen]=useState(false),[showTop,setShowTop]=useState(false),[settings,setSettings]=useState(loadSettings)
  useEffect(()=>{applySettings(settings);localStorage.setItem(STORAGE_KEY,JSON.stringify(settings))},[settings])
  useEffect(()=>{const update=()=>setShowTop((window.scrollY||document.documentElement.scrollTop||0)>320);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[])
  useEffect(()=>{if(!open)return;const close=(event)=>event.key==='Escape'&&setOpen(false);window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open])
  const toggle=(key)=>setSettings((current)=>({...current,[key]:!current[key]})),setFilter=(value)=>setSettings((current)=>({...current,colorFilter:value})),changeFont=(amount)=>setSettings((current)=>({...current,fontScale:Math.min(1.6,Math.max(.85,Number((current.fontScale+amount).toFixed(2))))}))
  return <>
    <div className="global-tools">
      <button type="button" className="a11y-floating-button" onClick={()=>setOpen(true)} aria-label={text.open} title={text.open}><Accessibility/></button>
      <button type="button" className={`scroll-top-floating-button${showTop?' is-visible':''}`} onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label={text.top} title={text.top} tabIndex={showTop?0:-1}><ArrowUp/></button>
    </div>
    {open&&<div className="a11y-layer"><button className="a11y-scrim" type="button" onClick={()=>setOpen(false)} aria-label={text.close}/><aside className="a11y-drawer" role="dialog" aria-modal="true" aria-label={text.title}>
      <button type="button" className="a11y-close" onClick={()=>setOpen(false)} aria-label={text.close}><X/></button>
      <div className="a11y-title"><Accessibility/><h2>{text.title}</h2><p>{text.subtitle}</p></div>
      <Section title={text.fontSize} icon={<Type/>}><div className="a11y-font-control"><button type="button" onClick={()=>changeFont(.1)}>+</button><div className="a11y-font-track"><span style={{width:`${Math.min(100,Math.max(0,((settings.fontScale-.85)/.75)*100))}%`}}/></div><button type="button" onClick={()=>changeFont(-.1)}>−</button><b>{Math.round(settings.fontScale*100)}%</b></div></Section>
      <Section title={text.colorModes} icon={<Palette/>}><Switch label={text.grayscale} active={settings.grayscale} onClick={()=>toggle('grayscale')} icon={<Eye/>}/><Switch label={text.invert} active={settings.invert} onClick={()=>toggle('invert')} icon={<Contrast/>}/><Switch label={text.lowSaturation} active={settings.lowSaturation} onClick={()=>toggle('lowSaturation')} icon={<Palette/>}/><div className="a11y-filter-title">{text.colorFilter}</div><div className="a11y-filter-grid">{['none','redGreen','blueYellow','red'].map((value)=><button type="button" key={value} className={settings.colorFilter===value?'active':''} onClick={()=>setFilter(value)}>{text[value]}</button>)}</div></Section>
      <Section title={text.visual} icon={<Eye/>}><Switch label={text.contrast} active={settings.contrast} onClick={()=>toggle('contrast')} icon={<Contrast/>}/><Switch label={text.bigText} active={settings.bigText} onClick={()=>toggle('bigText')} icon={<Type/>}/><Switch label={text.highlightLinks} active={settings.highlightLinks} onClick={()=>toggle('highlightLinks')} icon={<Palette/>}/><Switch label={text.underlineLinks} active={settings.underlineLinks} onClick={()=>toggle('underlineLinks')} icon={<Link2/>}/><Switch label={text.hideImages} active={settings.hideImages} onClick={()=>toggle('hideImages')} icon={<Eye/>}/></Section>
      <Section title={text.text} icon={<FileText/>}><Switch label={text.readableFont} active={settings.readableFont} onClick={()=>toggle('readableFont')} icon={<FileText/>}/><Switch label={text.lineSpacing} active={settings.lineSpacing} onClick={()=>toggle('lineSpacing')} icon={<Type/>}/><Switch label={text.letterSpacing} active={settings.letterSpacing} onClick={()=>toggle('letterSpacing')} icon={<Type/>}/><Switch label={text.alignLeft} active={settings.alignLeft} onClick={()=>toggle('alignLeft')} icon={<Type/>}/></Section>
      <Section title={text.navigation} icon={<MousePointer2/>}><Switch label={text.bigCursor} active={settings.bigCursor} onClick={()=>toggle('bigCursor')} icon={<MousePointer2/>}/><Switch label={text.reduceMotion} active={settings.reduceMotion} onClick={()=>toggle('reduceMotion')} icon={<RotateCcw/>}/><Switch label={text.stopAnimations} active={settings.stopAnimations} onClick={()=>toggle('stopAnimations')} icon={<RotateCcw/>}/></Section>
      <button type="button" className="a11y-reset" onClick={()=>setSettings({...defaults})}><RotateCcw/>{text.reset}</button>
    </aside></div>}
  </>
}

function Section({title,icon,children}){return <section className="a11y-section"><div className="a11y-section-title"><span>{title}</span>{icon}</div>{children}</section>}
function Switch({label,active,onClick,icon}){return <button type="button" className={`a11y-switch-row${active?' active':''}`} onClick={onClick} role="switch" aria-checked={active}><span className="a11y-switch-toggle"><span/></span><span className="a11y-switch-label">{label}</span><span className="a11y-row-icon">{icon}</span></button>}
