import {askConfirmation,showMessage} from './lib/site-dialogs'
import {useEffect,useState} from 'react'
import './lib/color-flow.css'
import './colors-panel.css'
import {colorNameKey,visibleColors,uniqueColors} from '../../shared/color-choices.mjs'
import {configurationFields,requiresColor,fieldName,defaultPalette} from '../../shared/product-configuration.mjs'
import {saveError} from './lib/save-errors'
const text={ar:{title:'الألوان',choose:'اختر اللون أولًا',products:'المنتجات التي تدعم اللون',sections:'تفاصيل اللون (اختيارية الآن)',pending:'يمكن تحديد التفاصيل لاحقًا داخل المنتج',save:'حفظ اللون وربطه بالمنتجات',saved:'تم حفظ اللون والمنتجات',local:'احفظ المنتج في صفحة المنتجات أولًا',assign:'تصنيفات اللون',unassigned:'اختر التفاصيل التابعة لهذا اللون',name:'اسم اللون',original:'اللون الأساسي'},en:{title:'Colors',choose:'Choose a color first',products:'Products supporting this color',sections:'Color details (optional now)',pending:'Assign details later in the product editor',save:'Save color and product assignments',saved:'Color and products saved',local:'Save the product in inventory first',assign:'Color classifications',unassigned:'Choose color details',name:'Color name',original:'Original color'},he:{title:'צבעים',choose:'בחר צבע תחילה',products:'מוצרים התומכים בצבע',sections:'פרטי צבע (רשות כעת)',pending:'ניתן לשייך פרטים בעריכת המוצר',save:'שמירת צבע ושיוך מוצרים',saved:'הצבע והמוצרים נשמרו',local:'יש לשמור מוצר במלאי תחילה',assign:'סיווגי צבע',unassigned:'בחר פרטי צבע',name:'שם צבע',original:'צבע מקורי'}}
export const colorPageText=language=>text[language]||text.en
const name=(product,language)=>product['name_'+language]||product.name_en
export function AdminColors({token,language,categories,refreshCatalog}){
 const c=colorPageText(language),copy=({ar:{add:'إضافة لون',shade:'اختر درجة اللون',cancel:'إلغاء',save:'حفظ اللون',choose:'اختر لونًا لعرضه أو حذفه',search:'ابحث عن منتج',selected:'منتجات مختارة',linked:'يدعم اللون',duplicate:'هذه الدرجة أو اسم اللون موجود بالفعل. استخدم اللون الموجود.',none:'لا توجد منتجات مطابقة',remove:'إزالة المنتج من الاختيار؟'},en:{add:'Add color',shade:'Choose color shade',cancel:'Cancel',save:'Save color',choose:'Select a color to view or delete it',search:'Search products',selected:'selected products',linked:'Supports color',duplicate:'This shade or name already exists. Use the existing color.',none:'No matching products',remove:'Remove this product from the selection?'},he:{add:'הוספת צבע',shade:'בחר גוון',cancel:'ביטול',save:'שמירת צבע',choose:'בחר צבע לצפייה או למחיקה',search:'חיפוש מוצרים',selected:'מוצרים נבחרים',linked:'תומך בצבע',duplicate:'הגוון כבר קיים. השתמש בצבע הקיים.',none:'אין מוצרים תואמים',remove:'להסיר מוצר זה מהבחירה?'}})[language]
 const [library,setLibrary]=useState([]),[color,setColor]=useState(null),[adding,setAdding]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const headers={Authorization:'Bearer '+token}
 const load=async()=>{try{const response=await fetch('/api/admin/colors',{headers});if(!response.ok)throw Error();setLibrary(visibleColors(await response.json()))}catch(e){setError(saveError(e,language))}}
 useEffect(()=>{load()},[token])
 const choose=value=>{setColor(value);setNotice('');setError('')}
 const send=async body=>{const response=await fetch('/api/admin/colors',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Object.assign(Error(data.error),data)}
 const duplicate=adding&&library.some(c=>c.hex.toLowerCase()===adding.hex.toLowerCase()||(colorNameKey(adding)&&colorNameKey(c)===colorNameKey(adding)))
 const create=async e=>{e.preventDefault();if(duplicate){await showMessage(copy.duplicate);return}setBusy(true);setError('');try{await send({color:adding,assignments:[],createOnly:true});const added={...adding,hex:adding.hex.toLowerCase()};await load();choose(added);setAdding(null);await showMessage(c.saved)}catch(e){setError(e.message==='color_exists'?copy.duplicate:saveError(e,language))}finally{setBusy(false)}}
 const removeColor=async()=>{if(busy||!color)return;const message=language==='ar'?'حذف اللون «'+color.name_ar+'» وكل تكرارات اسمه من قوائم المتجر والمنتجات والتفصيلات؟ تبقى الطلبات القديمة محفوظة.':language==='he'?'למחוק את הצבע מהמוצרים והפרטים? הזמנות קודמות נשמרות.':'Delete this color and duplicate names from products and details? Previous orders are preserved.';if(!await askConfirmation(message))return;setBusy(true);setError('');try{const r=await fetch('/api/admin/colors/'+color.hex.slice(1),{method:'DELETE',headers});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error),data);await Promise.all([load(),refreshCatalog()]);setColor(null);await showMessage(language==='ar'?'تم حذف اللون':language==='he'?'הצבע נמחק':'Color deleted')}catch(e){setError(e.message==='color_cleanup_limit'?'عدد الارتباطات كبير؛ لم يُحذف أي شيء.':saveError(e,language))}finally{setBusy(false)}}
 return <section className="inventory-page"><div className="colors-heading"><h2>{c.title}</h2><button className="button primary" disabled={busy} onClick={()=>{setError('');setAdding({hex:'#123456',name_ar:'',name_en:'',name_he:''})}}>+ {copy.add}</button></div><p>{copy.choose}</p><div className="color-library-grid">{library.map(value=><button type="button" disabled={busy} className={color?.hex===value.hex?'active':''} key={value.hex} onClick={()=>choose(value)} title={name(value,language)}><i style={{background:value.hex}}/>{name(value,language)}</button>)}</div>{color&&<div className="selected-color-heading"><i style={{background:color.hex}}/><h3>{name(color,language)}</h3><button type="button" className="button outline inventory-delete" disabled={busy} onClick={removeColor}>{language==='ar'?'حذف اللون':language==='he'?'מחיקת צבע':'Delete color'}</button></div>}{error&&!adding&&<p className="form-error">{error}</p>}{notice&&<p className="inventory-success">{notice}</p>}{adding&&<div className="modal-backdrop"><section className="modal color-add-modal" role="dialog" aria-modal="true" aria-label={copy.add}><form noValidate onSubmit={create}><fieldset disabled={busy}><h2>{copy.add}</h2><label>{copy.shade}<input type="color" value={adding.hex} onChange={e=>setAdding({...adding,hex:e.target.value})}/></label>{['ar','en','he'].map(l=><label key={l}>{c.name} · {l}<input required maxLength={80} dir={l==='en'?'ltr':'rtl'} value={adding['name_'+l]} onChange={e=>setAdding({...adding,['name_'+l]:e.target.value})}/></label>)}{duplicate&&<small>{copy.duplicate}</small>}{error&&<p className="form-error">{error}</p>}<div className="details-add-row"><button disabled={busy||duplicate} className="button primary">{copy.save}</button><button type="button" className="button outline" disabled={busy} onClick={()=>{setAdding(null);setError('')}}>{copy.cancel}</button></div></fieldset></form></section></div>}</section>
}
export function ProductColorAssignments({fields,options,setOptions,product,language,allFields=[],enabledColors,setEnabledColors,fieldLabels={},setFieldLabels}){
 const c=colorPageText(language),colorFields=fields.filter(requiresColor)
 const assign=(color,keys)=>{const next={...options};for(const field of colorFields){const old=next[field.key]||{},colors=(old.colors||[]).filter(x=>x.hex!==color.hex);if(keys.includes(field.key))colors.push(color);next[field.key]={...old,colors,defaultColor:null}}setOptions(next)}
return <section className="category-config-editor"><h3>{c.assign}</h3><div className="product-color-classifications">{allFields.filter(requiresColor).map(f=><fieldset key={f.key} className="detail-editor-card"><label className="config-checkbox"><input type="checkbox" checked={fields.some(x=>x.key===f.key)} onChange={async e=>{const checked=e.target.checked;if(!checked&&!await askConfirmation((language==='ar'?'إزالة تصنيف اللون؟':language==='he'?'להסיר סיווג צבע?':'Remove this color classification?')))return;const current=enabledColors??allFields.filter(requiresColor).map(x=>x.key);setEnabledColors(checked?[...current,f.key]:current.filter(k=>k!==f.key))}}/>{fieldName(f,language)}</label>{fields.some(x=>x.key===f.key)&&<div className="form-grid">{['ar','en','he'].map(l=><label key={l}>{c.assign} · {l}<input required maxLength={80} value={fieldLabels[f.key]?.['label_'+l]||f['label_'+l]} onChange={e=>setFieldLabels({...fieldLabels,[f.key]:{label_ar:f.label_ar,label_en:f.label_en,label_he:f.label_he,...fieldLabels[f.key],['label_'+l]:e.target.value}})}/></label>)}</div>}</fieldset>)}</div><p>{language==='ar'?'أضف الألوان من صفحة الألوان، وحدد هنا التفاصيل التابعة لكل لون.':language==='he'?'הוסף צבעים בעמוד הצבעים ושייך כאן לפרטי המוצר.':'Add colors on the Colors page, then assign their product details here.'}</p>{(colorFields.length?product.colors||[]:[]).map(color=><label className="detail-editor-card" key={color.hex}><span><i style={{background:color.hex,display:'inline-block',width:18,height:18,borderRadius:'50%',marginInlineEnd:8}}/>{name(color,language)}</span><select multiple required value={colorFields.filter(f=>options[f.key]?.colors?.some(x=>x.hex===color.hex)).map(f=>f.key)} onChange={async e=>{const keys=[...e.target.selectedOptions].map(o=>o.value),previous=colorFields.filter(f=>options[f.key]?.colors?.some(x=>x.hex===color.hex)).map(f=>f.key);if(previous.some(key=>!keys.includes(key))&&!await askConfirmation(language==='ar'?'إزالة ارتباط اللون من التفاصيل المحددة؟':language==='he'?'להסיר שיוך צבע מהפרטים?':'Remove this color from the selected details?'))return;assign(color,keys)}}>{colorFields.map(f=><option key={f.key} value={f.key}>{fieldName(f,language)}</option>)}</select><small>{c.unassigned}</small></label>)}{fields.filter(f=>f.textEnabled).map(f=><label key={f.key}>{fieldName(f,language)}<input value={options[f.key]?.defaultText||''} maxLength={30} onChange={e=>setOptions({...options,[f.key]:{...options[f.key],colors:[],defaultText:e.target.value}})}/></label>)}</section>
}




