import {useEffect,useState} from 'react'
import {showMessage,askConfirmation} from './lib/site-dialogs'
import {saveError} from './lib/save-errors'
import './details.css'
export const detailTitle=language=>language==='ar'?'التفصيلات':language==='he'?'פרטים':'Details'
const request=async(path,token,method='GET',body)=>{const r=await fetch(path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}),data=await r.json();if(!r.ok)throw Object.assign(Error(data.error),data);return data}
export function DetailSelector({fields,setFields,token}){
 const [available,setAvailable]=useState([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{let live=true;request('/api/admin/details',token).then(items=>{if(live)setAvailable(items)}).catch(()=>{if(live)setError('تعذر تحميل التفصيلات؛ أعد فتح الفئة.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[token])
 return <section className="details-selector"><h3>تفصيلات الفئة</h3><div className="details-add-row"><select disabled={loading} value={selected} onChange={e=>setSelected(e.target.value)} aria-label="اختر تفصيلًا"><option value="">{loading?'جارٍ التحميل…':'اختر تفصيلًا من صفحة التفصيلات'}</option>{available.filter(f=>!fields.some(x=>x.key===f.key)).map(f=><option key={f.key} value={f.key}>{f.label_ar}</option>)}</select><button type="button" className="button outline" disabled={!selected||fields.length>=30} onClick={()=>{const field=available.find(f=>f.key===selected);if(field)setFields([...fields,field]);setSelected('')}}>إضافة تفصيل</button></div>{error&&<p className="form-error">{error}</p>}{fields.map(field=><div className="details-selected-row" key={field.key}><span>{available.find(f=>f.key===field.key)?.label_ar||field.label_ar}</span><button type="button" className="button outline inventory-delete" onClick={async()=>{if(await askConfirmation('إزالة التفصيل من هذه الفئة؟ '+field.label_ar))setFields(fields.filter(f=>f.key!==field.key))}}>إزالة</button></div>)}<small>تعديل الاسم والنوع والألوان من صفحة التفصيلات فقط.</small></section>
}
export function AdminDetails({token,language,refreshCatalog}){
 const [details,setDetails]=useState([]),[colors,setColors]=useState([]),[editor,setEditor]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false)
 const load=async()=>{try{const [items,palette]=await Promise.all([request('/api/admin/details',token),request('/api/admin/colors',token)]);setDetails(items);setColors(palette);setLoaded(true)}catch(e){setError(saveError(e,language))}}
 useEffect(()=>{load()},[token])
 const open=item=>{setError('');setEditor(item?{...item,type:item.colorEnabled===false?'text':'color',colorHexes:(item.allowed_colors||[]).map(c=>c.hex)}:{label_ar:'',label_en:'',label_he:'',type:'color',placeholder_ar:'',placeholder_en:'',placeholder_he:'',colorHexes:[]})}
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{const body=Object.fromEntries(['label_ar','label_en','label_he','type','placeholder_ar','placeholder_en','placeholder_he','colorHexes'].map(k=>[k,editor[k]??(k==='colorHexes'?[]:'')]));await request('/api/admin/details'+(editor.key?'/'+editor.key:''),token,editor.key?'PATCH':'POST',body);await Promise.all([load(),refreshCatalog()]);setEditor(null);await showMessage('تم حفظ التفصيل')}catch(e){setError(e.message==='detail_type_in_use'?'لا يمكن تغيير نوع تفصيل مرتبط بفئة؛ أضف تفصيلًا جديدًا بدلًا منه.':saveError(e,language))}finally{setBusy(false)}}
 const remove=async item=>{if(busy||!await askConfirmation('حذف التفصيل؟ '+item.label_ar))return;setBusy(true);try{await request('/api/admin/details/'+item.key,token,'DELETE');await Promise.all([load(),refreshCatalog()])}catch(e){setError(e.message==='detail_in_use'?'التفصيل مستخدم في فئة أو منتج. أزل ارتباطه أولًا.':saveError(e,language))}finally{setBusy(false)}}
 return <section className="inventory-page"><button className="button primary" disabled={!loaded||busy} onClick={()=>open(null)}>إضافة تفصيل</button>{error&&!editor&&<p className="form-error">{error}</p>}<div className="inventory-grid">{details.map(f=><article className="inventory-card" key={f.key}><div><h3>{f.label_ar}</h3><p>{f.colorEnabled===false?'نص':'لون'}</p><small>{f.label_en} · {f.label_he}</small><div className="inventory-color-chips">{f.allowed_colors?.map(c=><i key={c.hex} style={{background:c.hex}} title={c.name_ar}/>)}</div><div className="details-add-row"><button disabled={busy} className="button outline" onClick={()=>open(f)}>تعديل</button><button disabled={busy} className="button outline inventory-delete" onClick={()=>remove(f)}>حذف</button></div></div></article>)}</div>{editor&&<div className="modal-backdrop"><section className="modal details-modal" role="dialog" aria-modal="true" aria-label="تعديل التفصيل"><form noValidate onSubmit={save}><fieldset disabled={busy}><h2>{editor.key?'تعديل التفصيل':'إضافة تفصيل'}</h2><label>نوع التفصيل<select value={editor.type} onChange={e=>setEditor({...editor,type:e.target.value})}><option value="color">لون</option><option value="text">نص</option></select></label><div className="form-grid">{['ar','en','he'].map(l=><label key={l}>اسم التفصيل · {l}<input required minLength={1} maxLength={80} dir={l==='en'?'ltr':'rtl'} value={editor['label_'+l]} onChange={e=>setEditor({...editor,['label_'+l]:e.target.value})}/></label>)}</div>{editor.type==='text'?<div className="form-grid">{['ar','en','he'].map(l=><label key={l}>النص المائي · {l}<input required maxLength={120} dir={l==='en'?'ltr':'rtl'} value={editor['placeholder_'+l]||''} onChange={e=>setEditor({...editor,['placeholder_'+l]:e.target.value})}/></label>)}</div>:<fieldset><legend>الألوان المسموحة للتفصيل — من صفحة الألوان</legend>{!colors.length&&<small>أضف الألوان من صفحة الألوان أولًا.</small>}<div className="detail-color-picker">{colors.map(c=><label key={c.hex}><input type="checkbox" checked={editor.colorHexes.includes(c.hex)} onChange={async e=>{const checked=e.target.checked;if(!checked&&!await askConfirmation('إزالة اللون من التفصيل؟ '+c.name_ar))return;setEditor(old=>({...old,colorHexes:checked?[...old.colorHexes,c.hex]:old.colorHexes.filter(h=>h!==c.hex)}))}}/><i style={{background:c.hex}}/>{c.name_ar}</label>)}</div><small>يظهر للمنتج فقط اللون الذي يدعمه المنتج ويسمح به هذا التفصيل.</small></fieldset>}{error&&<p className="form-error">{error}</p>}<div className="details-add-row"><button className="button primary" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ'}</button><button type="button" className="button outline" disabled={busy} onClick={()=>setEditor(null)}>إلغاء</button></div></fieldset></form></section></div>}</section>
}
