import {showMessage,askConfirmation} from './lib/site-dialogs'
import ProductDetails from './ProductDetails'
import {DetailSelector} from './AdminDetails'
import {saveError} from './lib/save-errors'
import {useEffect,useRef,useState} from 'react'
import {Plus,Pencil,X,Settings,Package,Palette} from 'lucide-react'
import {uploadFile,discardUpload} from './lib/uploads'
import {CategoryFieldsEditor,ProductFieldOptions} from './CategoryConfiguration'
import {configurationFields,splitConfigurationFields} from '../../shared/product-configuration.mjs'
import {categoryId} from '../../shared/catalog-categories.mjs'

const texts={
 ar:{products:'منتجات المحل',settings:'الإعدادات',add:'إضافة منتج',edit:'تعديل المنتج',category:'الفئة',addCategory:'إضافة فئة',editCategory:'تعديل الفئة',all:'كل الفئات',name:'اسم المنتج',ar:'بالعربية',en:'بالإنجليزية',he:'بالعبرية',price:'السعر ₪ — اتركه فارغًا للسعر عند التأكيد',dimensions:'الأبعاد بالسنتيمتر',length:'الطول',width:'العرض',height:'الارتفاع',colors:'ألوان المنتج المتاحة',addColor:'إضافة لون',colorName:'اسم اللون',image:'صورة المنتج JPEG / PNG / WebP — حتى 30 MiB',model:'مجسم GLB — حتى 30 MiB',save:'حفظ',cancel:'إلغاء',active:'ظاهر في المتجر',loading:'جارٍ التحميل…',empty:'لا توجد منتجات في هذه الفئة',error:'تعذر الحفظ أو التحميل، حاول مرة أخرى',saved:'تم الحفظ بنجاح',retry:'إعادة المحاولة',local:'منتج من ملفات العرض — حفظ تعديله يضيفه إلى قاعدة البيانات',currentPassword:'كلمة السر الحالية',newPassword:'كلمة السر الجديدة — 12 حرفًا على الأقل',confirm:'تأكيد كلمة السر الجديدة',changePassword:'تغيير كلمة السر',mismatch:'تأكيد كلمة السر غير مطابق',wrongPassword:'كلمة السر الحالية غير صحيحة',samePassword:'اختر كلمة سر مختلفة عن الحالية',changed:'تم تغيير كلمة السر. سجّل الدخول مجددًا.',login:'تسجيل الدخول مجددًا',filter:'ابحث باسم المنتج',remove:'إزالة',imageRequired:'أضف صورة للمنتج أولًا',categoryName:'اسم الفئة',passwordHint:'حتى 72 بايت. الجلسات الأخرى تبقى فعالة حتى انتهاء صلاحيتها.'},
 en:{products:'Store products',settings:'Settings',add:'Add product',edit:'Edit product',category:'Category',addCategory:'Add category',editCategory:'Edit category',all:'All categories',name:'Product name',ar:'Arabic',en:'English',he:'Hebrew',price:'Price ₪ — leave blank for price on request',dimensions:'Dimensions in centimetres',length:'Length',width:'Width',height:'Height',colors:'Available product colors',addColor:'Add color',colorName:'Color name',image:'Product image JPEG / PNG / WebP — up to 30 MiB',model:'GLB model — up to 30 MiB',save:'Save',cancel:'Cancel',active:'Visible in the store',loading:'Loading…',empty:'No products in this category',error:'Could not save or load. Please retry.',saved:'Saved successfully',retry:'Retry',local:'Display-file product — saving edits adds it to the database',currentPassword:'Current password',newPassword:'New password — at least 12 characters',confirm:'Confirm new password',changePassword:'Change password',mismatch:'Passwords do not match',wrongPassword:'Current password is incorrect',samePassword:'Choose a different password',changed:'Password changed. Please sign in again.',login:'Sign in again',filter:'Search product names',remove:'Remove',imageRequired:'Add a product image first',categoryName:'Category name',passwordHint:'Up to 72 bytes. Other sessions remain valid until they expire.'},
 he:{products:'מוצרי החנות',settings:'הגדרות',add:'הוספת מוצר',edit:'עריכת מוצר',category:'קטגוריה',addCategory:'הוספת קטגוריה',editCategory:'עריכת קטגוריה',all:'כל הקטגוריות',name:'שם המוצר',ar:'ערבית',en:'אנגלית',he:'עברית',price:'מחיר ₪ — השאר ריק למחיר בתיאום',dimensions:'מידות בסנטימטרים',length:'אורך',width:'רוחב',height:'גובה',colors:'צבעי המוצר הזמינים',addColor:'הוספת צבע',colorName:'שם הצבע',image:'תמונת JPEG / PNG / WebP — עד 30 MiB',model:'דגם GLB — עד 30 MiB',save:'שמירה',cancel:'ביטול',active:'מוצג בחנות',loading:'טוען…',empty:'אין מוצרים בקטגוריה',error:'השמירה או הטעינה נכשלה. נסה שוב.',saved:'נשמר בהצלחה',retry:'נסה שוב',local:'מוצר מקובצי התצוגה — שמירה מוסיפה אותו למסד הנתונים',currentPassword:'סיסמה נוכחית',newPassword:'סיסמה חדשה — לפחות 12 תווים',confirm:'אימות הסיסמה החדשה',changePassword:'שינוי סיסמה',mismatch:'הסיסמאות אינן תואמות',wrongPassword:'הסיסמה הנוכחית שגויה',samePassword:'בחר סיסמה שונה',changed:'הסיסמה שונתה. יש להתחבר מחדש.',login:'התחברות מחדש',filter:'חיפוש שם מוצר',remove:'הסרה',imageRequired:'הוסף תמונת מוצר תחילה',categoryName:'שם קטגוריה',passwordHint:'עד 72 בתים. הפעלות אחרות תקפות עד לפקיעתן.'},
}
export const inventoryText=language=>texts[language]||texts.en
Object.assign(texts.ar,{delete:'حذف',confirmProduct:'هل تريد حذف هذا المنتج من المتجر؟ تبقى الطلبات السابقة والملفات محفوظة.',confirmCategory:'هل تريد حذف هذه الفئة؟ لا يمكن حذف فئة مرتبطة بمنتجات.',categoryInUse:'الفئة تحتوي منتجات. احذف المنتجات أو انقلها لفئة أخرى أولًا.',deleted:'تم الحذف بنجاح'})
Object.assign(texts.en,{delete:'Delete',confirmProduct:'Delete this product from the store? Existing orders and files are preserved.',confirmCategory:'Delete this category? Categories containing products cannot be deleted.',categoryInUse:'This category has products. Delete or move them first.',deleted:'Deleted successfully'})
Object.assign(texts.he,{delete:'מחיקה',confirmProduct:'למחוק מוצר זה מהחנות? הזמנות קודמות וקבצים נשמרים.',confirmCategory:'למחוק קטגוריה זו? לא ניתן למחוק קטגוריה עם מוצרים.',categoryInUse:'יש מוצרים בקטגוריה. יש למחוק או להעביר אותם קודם.',deleted:'נמחק בהצלחה'})
const name=(item,language)=>item?.['name_'+language]||item?.name_en||item?.id||''
async function call(path,token,body,method=body?'POST':'GET'){
 const response=await fetch(path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})})
 const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(data.error||'request_failed'),data,{status:response.status});return data
}
function Dialog({title,close,busy,children}){
 const ref=useRef(null),back=useRef(null)
 useEffect(()=>{back.current=document.activeElement;ref.current?.focus();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;back.current?.focus()}},[])
 return <div className="inventory-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)close()}}><section className="inventory-dialog" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref} onKeyDown={e=>{if(e.key==='Escape'&&!busy)close();if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href]')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><header><h2>{title}</h2><button type="button" disabled={busy} onClick={close} aria-label="Close"><X/></button></header>{children}</section></div>
}
export function AdminInventory({token,language,categories,refreshCatalog,logout,storeProducts}){
 const c=inventoryText(language),[products,setProducts]=useState([]),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState(null),[categoryEditor,setCategoryEditor]=useState(null),[notice,setNotice]=useState('')
 const load=async()=>{setLoading(true);setError('');try{setProducts(await call('/api/admin/products',token))}catch(e){if(e.status===401)logout();else setError(c.error)}finally{setLoading(false)}}
 useEffect(()=>{load()},[token])
 const saved=async()=>{setEditor(null);setCategoryEditor(null);setNotice(c.saved);await Promise.all([load(),refreshCatalog()])}
 const [deleting,setDeleting]=useState(false)
 const remove=async(item,type)=>{if(deleting||!(await askConfirmation((type==='category'?c.confirmCategory:c.confirmProduct)+'\n'+name(item,language))))return;setDeleting(true);setError('');setNotice('');try{const path=type==='category'?'/api/admin/categories/'+encodeURIComponent(item.id):item.catalogOnly?'/api/admin/catalog-products/'+encodeURIComponent(item.slug):'/api/admin/products/'+item.id;await call(path,token,undefined,'DELETE');setFilter('all');await Promise.all([load(),refreshCatalog()]);setNotice(c.deleted)}catch(e){if(e.status===401)logout();else setError(e.message==='category_has_products'?c.categoryInUse:c.error)}finally{setDeleting(false)}}
 const label=id=>name(categories.find(c=>c.id===categoryId(id)),language)||id
 const filtered=products.filter(p=>(filter==='all'||categoryId(p.category)===filter)&&[p.name_ar,p.name_en,p.name_he].join(' ').toLowerCase().includes(query.toLowerCase()))
 return <section className="inventory-page"><div className="inventory-toolbar"><label><span>{c.category}</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{c.all}</option>{categories.map(x=><option key={x.id} value={x.id}>{name(x,language)}</option>)}</select></label><label><span>{c.filter}</span><input value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="button primary" onClick={()=>setEditor({})}><Plus size={18}/>{c.add}</button></div>{notice&&<p role="status" className="inventory-success">{notice}</p>}{error&&<p role="alert" className="form-error">{error}<button onClick={load}>{c.retry}</button></p>}{loading?<p role="status">{c.loading}</p>:<div className="inventory-grid">{!filtered.length&&<p className="empty">{c.empty}</p>}{filtered.map(p=><article key={p.slug} className="inventory-card"><img src={p.images?.[0]} alt={name(p,language)}/><div><span className="eyebrow">{label(p.category)}</span><h3>{name(p,language)}</h3><p>{p.price==null?'—':'₪'+Number(p.price).toFixed(2)}</p>{p.dimensions&&<small>{[p.dimensions.length,p.dimensions.width,p.dimensions.height].map(x=>x??'—').join(' × ')} cm</small>}{p.catalogOnly&&<small className="inventory-source">{c.local}</small>}<div className="inventory-color-chips">{p.colors?.map(color=><i key={color.hex} style={{background:color.hex}} title={name(color,language)}/>)}</div><button className="button outline" onClick={()=>{const storefront=storeProducts.find(x=>x.slug===p.slug);setEditor({...p,images:[...new Set([...(p.images||[]),...(storefront?.images||[])])]})}}><Pencil size={16}/>{c.edit}</button><button className="button outline inventory-delete" disabled={deleting} onClick={()=>remove(p,'product')}>{c.delete}</button></div></article>)}</div>}{editor&&<ProductEditor key={editor.slug||'new'} product={editor} token={token} language={language} categories={categories} close={()=>setEditor(null)} saved={saved}/ >}{categoryEditor&&<CategoryEditor key={categoryEditor.id||'new'} category={categoryEditor} token={token} language={language} close={()=>setCategoryEditor(null)} saved={saved}/>}</section>
}
function ProductEditor({product:p,token,language,categories,close,saved}){
 const c=inventoryText(language),[busy,setBusy]=useState(false),[error,setError]=useState(''),[palette,setPalette]=useState(p.colors||[]),[removed,setRemoved]=useState([]),[selectedCategory,setSelectedCategory]=useState(categoryId(p.category)),[fieldOptions,setFieldOptions]=useState(p.field_options||{}),[enabledColors,setEnabledColors]=useState(p.enabled_color_fields||null),[fieldLabels,setFieldLabels]=useState(p.field_labels||{})
 const allCategoryFields=configurationFields(categories.find(c=>c.id===selectedCategory),{...p,enabled_color_fields:null})
 const categoryFields=configurationFields(categories.find(c=>c.id===selectedCategory),{...p,enabled_color_fields:null,field_labels:{}})
 const editing=Boolean(p.id),existing=Boolean(p.slug)
 const submit=async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setError('');const claims=[]
  try{const image=data.get('image'),model=data.get('model'),images=(p.images||[]).filter(x=>!removed.includes(x));if(!editing&&!existing&&!image.size)throw Error('image_required');const body={enabledColorFields:allCategoryFields.filter(f=>f.colorEnabled!==false).map(f=>f.key),fieldLabels:{},nameAr:data.get('nameAr'),nameEn:data.get('nameEn'),nameHe:data.get('nameHe'),category:data.get('category'),price:data.get('price')===''?null:Number(data.get('price')),dimensions:Object.fromEntries(['length','width','height'].map(k=>[k,data.get(k)===''?null:Number(data.get(k))])),fieldOptions:Object.fromEntries(categoryFields.map(f=>[f.key,fieldOptions[f.key]]).filter(([,value])=>value)),colors:palette,images,modelParts:p.model_parts||{},customizableParts:p.customizable_parts?.length?p.customizable_parts:model.size?['rim']:palette.length?['body']:[]};if(!editing&&p.slug)body.slug=p.slug;if(image.size){body.imageUpload=await uploadFile(image,'productImage',token);claims.push(body.imageUpload)}if(model.size){body.modelUpload=await uploadFile(model,'productModel',token);claims.push(body.modelUpload)}await call(editing?'/api/admin/products/'+p.id:'/api/admin/products',token,body,editing?'PATCH':'POST');await saved()}catch(e){await Promise.all(claims.map(x=>discardUpload(x,token).catch(()=>{})));setError(e.message==='image_required'?c.imageRequired:saveError(e,language))}finally{setBusy(false)}
 }
 return <Dialog title={editing||existing?c.edit:c.add} close={close} busy={busy}><form noValidate onSubmit={submit}><fieldset disabled={busy}><div className="form-grid">{[['Ar','ar'],['En','en'],['He','he']].map(([suffix,lang])=><label key={lang}>{c.name} — {c[lang]}<input name={'name'+suffix} defaultValue={p['name_'+lang]||''} dir={lang==='en'?'ltr':'rtl'} lang={lang} required minLength={2} maxLength={190}/></label>)}<label>{c.category}<select name="category" value={selectedCategory} onChange={e=>{setSelectedCategory(e.target.value);setFieldOptions({});setEnabledColors(null);setFieldLabels({})}} required>{categories.map(x=><option key={x.id} value={x.id}>{name(x,language)}</option>)}</select></label><label>{c.price}<input name="price" type="number" min="0" max="99999999.99" step="0.01" defaultValue={p.price??''}/></label></div><h3>{c.dimensions}</h3><div className="inventory-dimensions">{['length','width','height'].map(k=><label key={k}>{c[k]}<input name={k} type="number" min="0.01" max="10000" step="0.01" defaultValue={p.dimensions?.[k]??''}/></label>)}</div><ProductDetails fields={categoryFields} options={fieldOptions} setOptions={setFieldOptions} product={p}/><div className="inventory-gallery">{(p.images||[]).filter(x=>!removed.includes(x)).map(url=><div key={url}><img src={url} alt=""/><button type="button" onClick={async()=>{if(await askConfirmation(c.remove+' — '+c.image+'؟'))setRemoved(current=>[...current,url])}} aria-label={c.remove}><X size={14}/></button></div>)}</div><div className="form-grid"><label>{c.image}<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/></label><label>{c.model}<input name="model" type="file" accept=".glb,model/gltf-binary"/></label></div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="inventory-form-actions"><button className="button primary" disabled={busy}>{busy?c.loading:c.save}</button><button className="button outline" type="button" disabled={busy} onClick={close}>{c.cancel}</button></div></fieldset></form></Dialog>
}
function CategoryEditor({category,token,language,close,saved}){
 const c=inventoryText(language),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState(()=>splitConfigurationFields(configurationFields(category,{customizable_parts:category.id==='wheel'?['rim','disc','caliper','stand','hub']:category.id==='turbo'?['airFilter','turboBody','fan','stand']:[]})))
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await call('/api/admin/categories'+(category.id?'/'+encodeURIComponent(category.id):''),token,{...Object.fromEntries(new FormData(e.currentTarget)),detailKeys:fields.map(f=>f.key)},category.id?'PATCH':'POST');await saved()}catch(e){setError(saveError(e,language))}finally{setBusy(false)}}
 return <Dialog title={category.id?c.editCategory:c.addCategory} close={close} busy={busy}><form noValidate onSubmit={submit}><fieldset disabled={busy}><div className="form-grid">{[['Ar','ar'],['En','en'],['He','he']].map(([suffix,lang])=><label key={lang}>{c.categoryName} — {c[lang]}<input name={'name'+suffix} lang={lang} dir={lang==='en'?'ltr':'rtl'} defaultValue={category['name_'+lang]||''} required minLength={2} maxLength={80}/></label>)}</div><DetailSelector fields={fields} setFields={setFields} token={token}/>{error&&<p className="form-error" role="alert">{error}</p>}<div className="inventory-form-actions"><button className="button primary">{busy?c.loading:c.save}</button><button className="button outline" type="button" onClick={close}>{c.cancel}</button></div></fieldset></form></Dialog>
}
export function AdminSettings({token,language,logout}){
 const c=inventoryText(language),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false)
 const submit=async e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form));setError('');if(data.newPassword!==data.confirm){setError(c.mismatch);return}setBusy(true);try{await call('/api/admin/change-password',token,{currentPassword:data.currentPassword,newPassword:data.newPassword});form.reset();setDone(true)}catch(e){setError(e.message==='invalid_current_password'?c.wrongPassword:e.message==='password_unchanged'?c.samePassword:c.error)}finally{setBusy(false)}}
 return <section className="inventory-settings"><h2><Settings size={22}/>{c.changePassword}</h2>{done?<div role="status"><p className="inventory-success">{c.changed}</p><button className="button primary" onClick={logout}>{c.login}</button></div>:<form noValidate onSubmit={submit}><fieldset disabled={busy}>{[['currentPassword',c.currentPassword,8,'current-password'],['newPassword',c.newPassword,12,'new-password'],['confirm',c.confirm,12,'new-password']].map(([key,label,min,autocomplete])=><label key={key}>{label}<input name={key} type="password" required minLength={min} maxLength={72} autoComplete={autocomplete}/></label>)}<small>{c.passwordHint}</small>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary">{busy?c.loading:c.save}</button></fieldset></form>}</section>
}

export function AdminCategories({token,language,categories,refreshCatalog,logout}){
 const c=inventoryText(language),[editor,setEditor]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const saved=async()=>{await refreshCatalog();setEditor(null);await showMessage(c.saved)}
 const remove=async item=>{if(busy||!await askConfirmation(c.confirmCategory+'\n'+name(item,language)))return;setBusy(true);try{await call('/api/admin/categories/'+encodeURIComponent(item.id),token,undefined,'DELETE');await refreshCatalog();await showMessage(c.deleted)}catch(e){if(e.status===401)logout();else setError(e.message==='category_has_products'?c.categoryInUse:saveError(e,language))}finally{setBusy(false)}}
 return <section className="inventory-page"><button className="button primary" onClick={()=>setEditor({})}><Plus/>{c.addCategory}</button>{error&&<p className="form-error">{error}</p>}<div className="inventory-grid">{categories.map(item=><article className="inventory-card" key={item.id}><div><h3>{name(item,language)}</h3><button className="button outline" disabled={busy} onClick={()=>setEditor(item)}>{c.editCategory}</button><button className="button outline inventory-delete" disabled={busy} onClick={()=>remove(item)}>{c.delete}</button></div></article>)}</div>{editor&&<CategoryEditor category={editor} token={token} language={language} close={()=>setEditor(null)} saved={saved}/>}</section>
}


