import {askConfirmation,showMessage} from './lib/site-dialogs'
import {useEffect,useState} from 'react'
import './lib/color-flow.css'
import './colors-panel.css'
import {uniqueColors} from '../../shared/color-choices.mjs'
import {configurationFields,requiresColor,fieldName,defaultPalette} from '../../shared/product-configuration.mjs'
import {saveError} from './lib/save-errors'
const text={ar:{title:'الألوان',choose:'اختر اللون أولًا',products:'المنتجات التي تدعم اللون',sections:'تفاصيل اللون (اختيارية الآن)',pending:'يمكن تحديد التفاصيل لاحقًا داخل المنتج',save:'حفظ اللون وربطه بالمنتجات',saved:'تم حفظ اللون والمنتجات',local:'احفظ المنتج في صفحة المنتجات أولًا',assign:'تصنيفات اللون',unassigned:'اختر التفاصيل التابعة لهذا اللون',name:'اسم اللون',original:'اللون الأساسي'},en:{title:'Colors',choose:'Choose a color first',products:'Products supporting this color',sections:'Color details (optional now)',pending:'Assign details later in the product editor',save:'Save color and product assignments',saved:'Color and products saved',local:'Save the product in inventory first',assign:'Color classifications',unassigned:'Choose color details',name:'Color name',original:'Original color'},he:{title:'צבעים',choose:'בחר צבע תחילה',products:'מוצרים התומכים בצבע',sections:'פרטי צבע (רשות כעת)',pending:'ניתן לשייך פרטים בעריכת המוצר',save:'שמירת צבע ושיוך מוצרים',saved:'הצבע והמוצרים נשמרו',local:'יש לשמור מוצר במלאי תחילה',assign:'סיווגי צבע',unassigned:'בחר פרטי צבע',name:'שם צבע',original:'צבע מקורי'}}
export const colorPageText=language=>text[language]||text.en
const name=(product,language)=>product['name_'+language]||product.name_en
export function AdminColors({token,language,categories,refreshCatalog}){
 const c=colorPageText(language),copy=({ar:{add:'إضافة لون',shade:'اختر درجة اللون',cancel:'إلغاء',save:'حفظ اللون',choose:'اختر لونًا موجودًا لإضافته إلى منتجات أخرى',search:'ابحث عن منتج',selected:'منتجات مختارة',linked:'يدعم اللون',duplicate:'هذه الدرجة موجودة بالفعل. اختر اللون الموجود لإضافته إلى منتج آخر.',none:'لا توجد منتجات مطابقة',remove:'إزالة المنتج من الاختيار؟'},en:{add:'Add color',shade:'Choose color shade',cancel:'Cancel',save:'Save color',choose:'Select an existing color to assign it to more products',search:'Search products',selected:'selected products',linked:'Supports color',duplicate:'This shade already exists. Select the existing color to assign it to more products.',none:'No matching products',remove:'Remove this product from the selection?'},he:{add:'הוספת צבע',shade:'בחר גוון',cancel:'ביטול',save:'שמירת צבע',choose:'בחר צבע קיים כדי לשייך למוצרים נוספים',search:'חיפוש מוצרים',selected:'מוצרים נבחרים',linked:'תומך בצבע',duplicate:'הגוון כבר קיים. בחר את הצבע הקיים לשיוך למוצר נוסף.',none:'אין מוצרים תואמים',remove:'להסיר מוצר זה מהבחירה?'}})[language]
 const [products,setProducts]=useState([]),[library,setLibrary]=useState([]),[color,setColor]=useState(null),[selected,setSelected]=useState([]),[search,setSearch]=useState(''),[adding,setAdding]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const headers={Authorization:'Bearer '+token}
 const load=async()=>{try{const responses=await Promise.all(['/api/admin/products','/api/admin/colors'].map(path=>fetch(path,{headers})));if(responses.some(r=>!r.ok))throw Error();const [items,colors]=await Promise.all(responses.map(r=>r.json()));setProducts(items);setLibrary(uniqueColors([...items.flatMap(p=>p.colors||[]),...colors]))}catch(e){setError(saveError(e,language))}}
 useEffect(()=>{load()},[token])
 const choose=value=>{setColor(value);setSelected([]);setSearch('');setNotice('');setError('')}
 const send=async body=>{const response=await fetch('/api/admin/colors',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Object.assign(Error(data.error),data)}
 const duplicate=adding&&library.some(c=>c.hex.toLowerCase()===adding.hex.toLowerCase())
 const create=async e=>{e.preventDefault();if(duplicate){await showMessage(copy.duplicate);return}setBusy(true);setError('');try{await send({color:adding,assignments:[],createOnly:true});const added={...adding,hex:adding.hex.toLowerCase()};await load();choose(added);setAdding(null);await showMessage(c.saved)}catch(e){setError(e.message==='color_exists'?copy.duplicate:saveError(e,language))}finally{setBusy(false)}}
 const save=async e=>{e.preventDefault();if(!color||!selected.length)return;setBusy(true);setError('');setNotice('');try{await send({color,assignments:selected.map(productId=>({productId,fields:[]}))});await Promise.all([load(),refreshCatalog()]);setSelected([]);setNotice(c.saved)}catch(e){setError(saveError(e,language))}finally{setBusy(false)}}
 const toggle=async(p,checked)=>{if(!checked&&!await askConfirmation(copy.remove+' '+name(p,language)))return;setSelected(ids=>checked?[...new Set([...ids,p.id])]:ids.filter(id=>id!==p.id))}
 const matches=products.filter(p=>[p.name_ar,p.name_en,p.name_he].join(' ').toLowerCase().includes(search.toLowerCase()))
 return <section className="inventory-page"><div className="colors-heading"><h2>{c.title}</h2><button className="button primary" disabled={busy} onClick={()=>{setError('');setAdding({hex:'#123456',name_ar:'',name_en:'',name_he:''})}}>+ {copy.add}</button></div><p>{copy.choose}</p><div className="color-library-grid">{library.map(value=><button type="button" disabled={busy} className={color?.hex===value.hex?'active':''} key={value.hex} onClick={()=>choose(value)} title={name(value,language)}><i style={{background:value.hex}}/>{name(value,language)}</button>)}</div>{color&&<form noValidate onSubmit={save}><fieldset disabled={busy}><div className="selected-color-heading"><i style={{background:color.hex}}/><h3>{name(color,language)}</h3></div><h3>{c.products}</h3><details className="color-product-dropdown"><summary>{c.products} · {selected.length} {copy.selected}</summary><div className="color-product-menu"><input aria-label={copy.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder={copy.search}/><div className="color-product-options">{!matches.length&&<p>{copy.none}</p>}{matches.map(p=><label className="color-product-option" key={p.slug}><input type="checkbox" disabled={!p.id} checked={selected.includes(p.id)} onChange={e=>toggle(p,e.target.checked)}/>{p.images?.[0]&&<img src={p.images[0]} alt=""/>}<span>{name(p,language)}</span>{!p.id?<small>{c.local}</small>:p.colors?.some(x=>x.hex.toLowerCase()===color.hex)&&<small>✓ {copy.linked}</small>}</label>)}</div></div></details><div className="color-targets">{products.filter(p=>selected.includes(p.id)).map(p=><button type="button" key={p.id} onClick={()=>toggle(p,false)}>{name(p,language)} ×</button>)}</div><button disabled={!selected.length||busy} className="button primary">{c.save}</button></fieldset></form>}{error&&!adding&&<p className="form-error">{error}</p>}{notice&&<p className="inventory-success">{notice}</p>}{adding&&<div className="modal-backdrop"><section className="modal color-add-modal" role="dialog" aria-modal="true" aria-label={copy.add}><form noValidate onSubmit={create}><fieldset disabled={busy}><h2>{copy.add}</h2><label>{copy.shade}<input type="color" value={adding.hex} onChange={e=>setAdding({...adding,hex:e.target.value})}/></label>{['ar','en','he'].map(l=><label key={l}>{c.name} · {l}<input required maxLength={80} dir={l==='en'?'ltr':'rtl'} value={adding['name_'+l]} onChange={e=>setAdding({...adding,['name_'+l]:e.target.value})}/></label>)}{duplicate&&<small>{copy.duplicate}</small>}{error&&<p className="form-error">{error}</p>}<div className="details-add-row"><button disabled={busy||duplicate} className="button primary">{copy.save}</button><button type="button" className="button outline" disabled={busy} onClick={()=>{setAdding(null);setError('')}}>{copy.cancel}</button></div></fieldset></form></section></div>}</section>
}
export function ProductColorAssignments({fields,options,setOptions,product,language,allFields=[],enabledColors,setEnabledColors,fieldLabels={},setFieldLabels}){
 const c=colorPageText(language),colorFields=fields.filter(requiresColor)
 const assign=(color,keys)=>{const next={...options};for(const field of colorFields){const old=next[field.key]||{},colors=(old.colors||[]).filter(x=>x.hex!==color.hex);if(keys.includes(field.key))colors.push(color);next[field.key]={...old,colors,defaultColor:null}}setOptions(next)}
return <section className="category-config-editor"><h3>{c.assign}</h3><div className="product-color-classifications">{allFields.filter(requiresColor).map(f=><fieldset key={f.key} className="detail-editor-card"><label className="config-checkbox"><input type="checkbox" checked={fields.some(x=>x.key===f.key)} onChange={async e=>{const checked=e.target.checked;if(!checked&&!await askConfirmation((language==='ar'?'إزالة تصنيف اللون؟':language==='he'?'להסיר סיווג צבע?':'Remove this color classification?')))return;const current=enabledColors??allFields.filter(requiresColor).map(x=>x.key);setEnabledColors(checked?[...current,f.key]:current.filter(k=>k!==f.key))}}/>{fieldName(f,language)}</label>{fields.some(x=>x.key===f.key)&&<div className="form-grid">{['ar','en','he'].map(l=><label key={l}>{c.assign} · {l}<input required maxLength={80} value={fieldLabels[f.key]?.['label_'+l]||f['label_'+l]} onChange={e=>setFieldLabels({...fieldLabels,[f.key]:{label_ar:f.label_ar,label_en:f.label_en,label_he:f.label_he,...fieldLabels[f.key],['label_'+l]:e.target.value}})}/></label>)}</div>}</fieldset>)}</div><p>{language==='ar'?'أضف الألوان من صفحة الألوان، وحدد هنا التفاصيل التابعة لكل لون.':language==='he'?'הוסף צבעים בעמוד הצבעים ושייך כאן לפרטי המוצר.':'Add colors on the Colors page, then assign their product details here.'}</p>{(colorFields.length?product.colors||[]:[]).map(color=><label className="detail-editor-card" key={color.hex}><span><i style={{background:color.hex,display:'inline-block',width:18,height:18,borderRadius:'50%',marginInlineEnd:8}}/>{name(color,language)}</span><select multiple required value={colorFields.filter(f=>options[f.key]?.colors?.some(x=>x.hex===color.hex)).map(f=>f.key)} onChange={async e=>{const keys=[...e.target.selectedOptions].map(o=>o.value),previous=colorFields.filter(f=>options[f.key]?.colors?.some(x=>x.hex===color.hex)).map(f=>f.key);if(previous.some(key=>!keys.includes(key))&&!await askConfirmation(language==='ar'?'إزالة ارتباط اللون من التفاصيل المحددة؟':language==='he'?'להסיר שיוך צבע מהפרטים?':'Remove this color from the selected details?'))return;assign(color,keys)}}>{colorFields.map(f=><option key={f.key} value={f.key}>{fieldName(f,language)}</option>)}</select><small>{c.unassigned}</small></label>)}{fields.filter(f=>f.textEnabled).map(f=><label key={f.key}>{fieldName(f,language)}<input value={options[f.key]?.defaultText||''} maxLength={30} onChange={e=>setOptions({...options,[f.key]:{...options[f.key],colors:[],defaultText:e.target.value}})}/></label>)}</section>
}


