import {askConfirmation} from './lib/site-dialogs'
import {useEffect,useState} from 'react'
import './lib/color-flow.css'
import {configurationFields,requiresColor,fieldName,defaultPalette} from '../../shared/product-configuration.mjs'
import {saveError} from './lib/save-errors'
const text={ar:{title:'الألوان',choose:'اختر اللون أولًا',products:'المنتجات التي تدعم اللون',sections:'تفاصيل اللون (اختيارية الآن)',pending:'يمكن تحديد التفاصيل لاحقًا داخل المنتج',save:'حفظ اللون وربطه بالمنتجات',saved:'تم حفظ اللون والمنتجات',local:'احفظ المنتج في صفحة المنتجات أولًا',assign:'تصنيفات اللون',unassigned:'اختر التفاصيل التابعة لهذا اللون',name:'اسم اللون',original:'اللون الأساسي'},en:{title:'Colors',choose:'Choose a color first',products:'Products supporting this color',sections:'Color details (optional now)',pending:'Assign details later in the product editor',save:'Save color and product assignments',saved:'Color and products saved',local:'Save the product in inventory first',assign:'Color classifications',unassigned:'Choose color details',name:'Color name',original:'Original color'},he:{title:'צבעים',choose:'בחר צבע תחילה',products:'מוצרים התומכים בצבע',sections:'פרטי צבע (רשות כעת)',pending:'ניתן לשייך פרטים בעריכת המוצר',save:'שמירת צבע ושיוך מוצרים',saved:'הצבע והמוצרים נשמרו',local:'יש לשמור מוצר במלאי תחילה',assign:'סיווגי צבע',unassigned:'בחר פרטי צבע',name:'שם צבע',original:'צבע מקורי'}}
export const colorPageText=language=>text[language]||text.en
const name=(product,language)=>product['name_'+language]||product.name_en
export function AdminColors({token,language,categories,refreshCatalog}){
 const c=colorPageText(language),[products,setProducts]=useState([]),[library,setLibrary]=useState([]),[color,setColor]=useState({hex:'#101114',name_ar:'',name_en:'',name_he:''}),[assignments,setAssignments]=useState({}),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const headers={Authorization:'Bearer '+token}
 const load=async()=>{try{const responses=await Promise.all(['/api/admin/products','/api/admin/colors'].map(path=>fetch(path,{headers})));if(responses.some(r=>!r.ok))throw Error();const [items,colors]=await Promise.all(responses.map(r=>r.json()));setProducts(items);setLibrary([...new Map([...items.flatMap(p=>p.colors||[]),...colors].map(c=>[c.hex,c])).values()])}catch(e){setError(saveError(e,language))}}
 useEffect(()=>{load()},[token])
 const choose=color=>{setColor(color);setAssignments({});setNotice('')}
 const save=async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/admin/colors',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({color,assignments:Object.entries(assignments).map(([productId,fields])=>({productId:Number(productId),fields}))})});const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error),data);setNotice(c.saved);setAssignments({});await Promise.all([load(),refreshCatalog()])}catch(e){setError(saveError(e,language))}finally{setBusy(false)}}
 return <section className="inventory-page"><h2>{c.title}</h2><div className="inventory-color-chips">{library.map(color=><button type="button" key={color.hex} onClick={()=>choose(color)} title={name(color,language)} style={{borderColor:color.hex}}><i style={{background:color.hex,display:'inline-block',width:18,height:18,borderRadius:'50%',verticalAlign:'middle',marginInlineEnd:8}}/>{name(color,language)}</button>)}</div><form noValidate onSubmit={save}><fieldset disabled={busy}><h3>{c.choose}</h3><div className="form-grid"><label>{c.choose}<select value="" onChange={e=>{const preset=defaultPalette.find(x=>x.hex===e.target.value);if(preset)choose({hex:preset.hex,name_ar:preset.ar,name_en:preset.en,name_he:preset.he})}}><option value="">—</option>{defaultPalette.map(p=><option key={p.hex} value={p.hex}>{p[language]||p.en}</option>)}</select><input type="color" value={color.hex} onChange={e=>setColor({...color,hex:e.target.value})}/></label>{['ar','en','he'].map(l=><label key={l}>{c.name} · {l}<input required maxLength={80} value={color['name_'+l]} onChange={e=>setColor({...color,['name_'+l]:e.target.value})}/></label>)}</div><h3>{c.products}</h3><input aria-label={c.products} value={search} onChange={e=>setSearch(e.target.value)}/><div className="color-product-list">{products.filter(p=>name(p,language).toLowerCase().includes(search.toLowerCase())).map(p=><div className="detail-editor-card" key={p.slug}><label className="config-checkbox"><input type="checkbox" disabled={!p.id} checked={assignments[p.id]!==undefined} onChange={e=>setAssignments(old=>{const next={...old};if(e.target.checked)next[p.id]=[];else delete next[p.id];return next})}/>{name(p,language)}{!p.id&&<small>{c.local}</small>}</label>{assignments[p.id]!==undefined&&<label>{c.sections}<select multiple value={assignments[p.id]} onChange={e=>setAssignments({...assignments,[p.id]:[...e.target.selectedOptions].map(o=>o.value)})}>{configurationFields(categories.find(x=>x.id===p.category),p).filter(requiresColor).map(f=><option key={f.key} value={f.key}>{fieldName(f,language)}</option>)}</select><small>{c.pending}</small></label>}</div>)}</div><button className="button primary">{c.save}</button></fieldset></form>{error&&<p className="form-error">{error}</p>}{notice&&<p className="inventory-success">{notice}</p>}</section>
}
export function ProductColorAssignments({fields,options,setOptions,product,language,allFields=[],enabledColors,setEnabledColors,fieldLabels={},setFieldLabels}){
 const c=colorPageText(language),colorFields=fields.filter(requiresColor)
 const assign=(color,keys)=>{const next={...options};for(const field of colorFields){const old=next[field.key]||{},colors=(old.colors||[]).filter(x=>x.hex!==color.hex);if(keys.includes(field.key))colors.push(color);next[field.key]={...old,colors,defaultColor:null}}setOptions(next)}
return <section className="category-config-editor"><h3>{c.assign}</h3><div className="product-color-classifications">{allFields.filter(requiresColor).map(f=><fieldset key={f.key} className="detail-editor-card"><label className="config-checkbox"><input type="checkbox" checked={fields.some(x=>x.key===f.key)} onChange={async e=>{const checked=e.target.checked;if(!checked&&!await askConfirmation((language==='ar'?'إزالة تصنيف اللون؟':language==='he'?'להסיר סיווג צבע?':'Remove this color classification?')))return;const current=enabledColors??allFields.filter(requiresColor).map(x=>x.key);setEnabledColors(checked?[...current,f.key]:current.filter(k=>k!==f.key))}}/>{fieldName(f,language)}</label>{fields.some(x=>x.key===f.key)&&<div className="form-grid">{['ar','en','he'].map(l=><label key={l}>{c.assign} · {l}<input required maxLength={80} value={fieldLabels[f.key]?.['label_'+l]||f['label_'+l]} onChange={e=>setFieldLabels({...fieldLabels,[f.key]:{label_ar:f.label_ar,label_en:f.label_en,label_he:f.label_he,...fieldLabels[f.key],['label_'+l]:e.target.value}})}/></label>)}</div>}</fieldset>)}</div><p>{language==='ar'?'أضف الألوان من صفحة الألوان، وحدد هنا التفاصيل التابعة لكل لون.':language==='he'?'הוסף צבעים בעמוד הצבעים ושייך כאן לפרטי המוצר.':'Add colors on the Colors page, then assign their product details here.'}</p>{(colorFields.length?product.colors||[]:[]).map(color=><label className="detail-editor-card" key={color.hex}><span><i style={{background:color.hex,display:'inline-block',width:18,height:18,borderRadius:'50%',marginInlineEnd:8}}/>{name(color,language)}</span><select multiple required value={colorFields.filter(f=>options[f.key]?.colors?.some(x=>x.hex===color.hex)).map(f=>f.key)} onChange={async e=>{const keys=[...e.target.selectedOptions].map(o=>o.value),previous=colorFields.filter(f=>options[f.key]?.colors?.some(x=>x.hex===color.hex)).map(f=>f.key);if(previous.some(key=>!keys.includes(key))&&!await askConfirmation(language==='ar'?'إزالة ارتباط اللون من التفاصيل المحددة؟':language==='he'?'להסיר שיוך צבע מהפרטים?':'Remove this color from the selected details?'))return;assign(color,keys)}}>{colorFields.map(f=><option key={f.key} value={f.key}>{fieldName(f,language)}</option>)}</select><small>{c.unassigned}</small></label>)}{fields.filter(f=>f.textEnabled).map(f=><label key={f.key}>{fieldName(f,language)}<input value={options[f.key]?.defaultText||''} maxLength={30} onChange={e=>setOptions({...options,[f.key]:{...options[f.key],colors:[],defaultText:e.target.value}})}/></label>)}</section>
}

