import {useState} from 'react'
import {configurationFields,fieldPalette,fieldName,defaultPalette,requiresColor,applyColorsToFields} from '../../shared/product-configuration.mjs'
export const configurationCopy={
 ar:{fields:'تفاصيل تخصيص الفئة',add:'إضافة تفصيل',color:'لون',applyAll:'إضافة هذه الألوان إلى كل تفاصيل اللون',remove:'حذف التفصيل',text:'نص',allowed:'الألوان المسموحة لهذا التفصيل',default:'اللون الأساسي للمنتج',defaultText:'النص الأساسي للمنتج (لا يملأ حقل الزبون)',choose:'اختر اللون',required:'اختر كل الألوان واكتب النصوص المطلوبة أولًا',write:'اكتب النص المطلوب',inferred:'قيمة أساسية'},
 en:{fields:'Category customization fields',add:'Add detail',color:'Color',applyAll:'Apply these colors to all color details',remove:'Remove field',text:'Text',allowed:'Allowed colors for this field',default:'Original product color',defaultText:'Original product text (not prefilled for customer)',choose:'Choose a color',required:'Choose all colors and enter required text first',write:'Enter your text',inferred:'Original value'},
 he:{fields:'פרטי התאמה לקטגוריה',add:'הוספת פרט',color:'צבע',applyAll:'החלת הצבעים על כל פרטי הצבע',remove:'הסרת שדה',text:'טקסט',allowed:'צבעים מותרים לשדה',default:'צבע מקורי של המוצר',defaultText:'טקסט מקורי (לא ממולא מראש ללקוח)',choose:'בחירת צבע',required:'בחר את כל הצבעים והזן את הטקסט הנדרש',write:'הזן טקסט',inferred:'ערך מקורי'}
}
export function CategoryFieldsEditor({fields,setFields,language}){
 const c=configurationCopy[language]||configurationCopy.en,[adding,setAdding]=useState(false),[type,setType]=useState('color')
 const captions=language==='ar'?{color:'تفاصيل الألوان',text:'تفاصيل النصوص',title:'عنوان التفصيل',placeholder:'النص المائي الذي يظهر للزبون',add:'إضافة',cancel:'إلغاء'}:language==='he'?{color:'פרטי צבע',text:'פרטי טקסט',title:'כותרת הפרט',placeholder:'טקסט מציין מקום ללקוח',add:'הוספה',cancel:'ביטול'}:{color:'Color details',text:'Text details',title:'Detail title',placeholder:'Customer input placeholder',add:'Add',cancel:'Cancel'}
 const update=(key,data)=>setFields(fields.map(f=>f.key===key?{...f,...data}:f))
 return <section className="category-config-editor organized-details"><header className="details-toolbar"><h3>{c.fields}</h3><button type="button" className="button outline" disabled={fields.length>=30} onClick={()=>setAdding(!adding)}>{c.add}</button></header>{adding&&<div className="new-detail-choice"><div className="field-type-switch"><label className="config-checkbox"><input type="checkbox" checked={type==='color'} onChange={()=>setType('color')}/>{c.color}</label><label className="config-checkbox"><input type="checkbox" checked={type==='text'} onChange={()=>setType('text')}/>{c.text}</label></div><button type="button" className="button primary" onClick={()=>{setFields([...fields,{key:'part'+Date.now(),label_ar:'',label_en:'',label_he:'',colorEnabled:type==='color',textEnabled:type==='text',...(type==='text'?{placeholder_ar:'',placeholder_en:'',placeholder_he:''}:{})}]);setAdding(false)}}>{captions.add}</button><button type="button" className="button outline" onClick={()=>setAdding(false)}>{captions.cancel}</button></div>}{['color','text'].map(kind=><div key={kind} className="detail-kind-section"><h4>{captions[kind]}</h4>{fields.filter(f=>kind==='color'?requiresColor(f):f.textEnabled).map(f=><fieldset className="detail-editor-card" key={f.key}><legend>{fieldName(f,language)||captions.title}</legend><div className="form-grid">{['ar','en','he'].map(l=><label key={l}>{captions.title} · {l}<input value={f['label_'+l]} required maxLength={80} dir={l==='en'?'ltr':'rtl'} onChange={e=>update(f.key,{['label_'+l]:e.target.value})}/></label>)}</div>{kind==='text'&&<div className="form-grid">{['ar','en','he'].map(l=><label key={l}>{captions.placeholder} · {l}<input value={f['placeholder_'+l]||''} required maxLength={120} dir={l==='en'?'ltr':'rtl'} onChange={e=>update(f.key,{['placeholder_'+l]:e.target.value})}/></label>)}</div>}<button type="button" className="button outline inventory-delete" onClick={()=>setFields(fields.filter(x=>x.key!==f.key))}>{c.remove}</button></fieldset>)}</div>)}</section>
}
export function ProductFieldOptions({fields,options,setOptions,product,palette,language}){
 const c=configurationCopy[language]||configurationCopy.en
 const change=(key,data)=>setOptions({...options,[key]:{...options[key],...data}})
 return <section className="category-config-editor"><h3>{c.fields}</h3>{fields.map(f=>{
 const inherited=fieldPalette({...product,colors:palette},f.key),selected=options[f.key]?.colors||inherited,available=[...new Map([...inherited,...selected,...(palette.length?palette:defaultPalette.map(c=>({hex:c.hex,name_ar:c.ar,name_en:c.en,name_he:c.he})))].map(x=>[x.hex.toLowerCase(),x])).values()]
 return <fieldset key={f.key}><legend>{fieldName(f,language)}</legend>{requiresColor(f)&&<><p>{c.allowed}</p><div className="field-palette-options">{available.map(color=><label key={color.hex}><input type="checkbox" checked={selected.some(x=>x.hex===color.hex)} onChange={e=>change(f.key,{colors:e.target.checked?[...selected,color]:selected.filter(x=>x.hex!==color.hex)})}/><i style={{background:color.hex}}/>{color['name_'+language]||color.name_en}</label>)}</div><label>{c.default}<select value={options[f.key]?.defaultColor||''} required onChange={e=>change(f.key,{colors:selected,defaultColor:e.target.value})}><option value="">{c.choose}</option>{selected.map(color=><option key={color.hex} value={color.hex}>{color['name_'+language]||color.name_en}</option>)}</select></label><button type="button" className="button outline" disabled={!selected.length} onClick={()=>setOptions(applyColorsToFields(fields,options,selected))}>{c.applyAll}</button></>}{f.textEnabled&&<label>{c.defaultText}<input value={options[f.key]?.defaultText||''} required maxLength={f.key==='caliper'?20:30} onChange={e=>change(f.key,{colors:requiresColor(f)?selected:[],defaultColor:requiresColor(f)?options[f.key]?.defaultColor:null,defaultText:e.target.value})}/></label>}</fieldset>})}</section>
}



