export const dictionaries = {
  ar: {
    home:'الرئيسية', back:'العودة', products:'المنتجات', custom:'طلب خاص', about:'من نحن', contact:'تواصل معنا', admin:'الإدارة',
    heroEyebrow:'فن السيارات بتقنية ثلاثية الأبعاد', heroTitle:'حوّل شغفك بالسيارات إلى قطعة لا تتكرر.', heroText:'مجسمات مطبوعة ثلاثية الأبعاد، مصقولة يدويًا ومخصصة بألوانك ونصوصك.', shopNow:'اكتشف المجموعة', customCta:'اصنع فكرتك',
    categories:'صُممت لعشّاق التفاصيل', categoryText:'اختر الطراز ثم عدّل كل قطعة حتى يصبح المجسم لك وحدك.', wheels:'مجسمات الجنوط', turbo:'مجسمات التيربو', shelves:'الرفوف', keychains:'علاقات المفاتيح', photos:'صور', catalogSearch:'ابحث عن منتج', noProducts:'لا توجد منتجات مطابقة', premium:'جودة ممتازة', precision:'طباعة دقيقة', personalization:'تخصيص كامل', support:'تواصل مباشر',
    collection:'المجموعة', collectionTitle:'اختَر مجسمك القادم', collectionText:'صور حقيقية للمنتجات مع معاينة ثلاثية الأبعاد.', viewProduct:'خصّص المنتج', from:'ابتداءً من',
    product:'المنتج', customize:'خصص منتجك', drag:'اسحب لتدوير المجسم 360°', rim:'الجنط', disc:'قرص الفرامل', caliper:'الكاليبر', stand:'القاعدة', hub:'القطعة الوسطية', colors:'الألوان', baseText:'النص على القاعدة', caliperText:'النص على الكاليبر', optional:'اختياري', quantity:'الكمية', orderNow:'أرسل الطلب', yourDetails:'بيانات التوصيل', name:'الاسم الكامل', phone:'رقم الهاتف', code:'رمز البلد', country:'اسم البلد', address:'مكان التوصيل بالتفصيل', notes:'ملاحظات', sending:'جارٍ إرسال الطلب...', success:'وصلنا طلبك بنجاح', successText:'رقم طلبك', error:'تعذر إرسال الطلب. تحقق من البيانات أو اتصال الخادم.', invalidFields:'الحقول التي تحتاج مراجعة', customerName:'الاسم الكامل', countryCode:'رمز البلد', deliveryAddress:'عنوان التوصيل', deliveryLat:'موقع التوصيل', deliveryLng:'موقع التوصيل',
    customTitle:'لديك فكرة خاصة؟ لنطبعها.', customText:'ارفع صورة واضحة، اكتب اسم القطعة والألوان المطلوبة، وسنتواصل معك لتحديد السعر ومدة التجهيز.', customName:'اسم المنتج أو القطعة', partsDescription:'اشرح القطع وألوان كل قطعة', upload:'ارفع صورة مرجعية', submitCustom:'أرسل الطلب الخاص',
    aboutTitle:'من الفكرة إلى قطعة تستحق العرض', aboutText:'في Revtrove نصنع ديكورات سيارات مطبوعة ثلاثية الأبعاد بعناية، من أول طبقة حتى اللمسة الأخيرة. كل طلب يمر بمراجعة وتجهيز يدوي.',
    contactTitle:'لنتحدث عن مشروعك', call:'اتصل بنا', instagram:'إنستاغرام', email:'البريد الإلكتروني', rights:'جميع الحقوق محفوظة.', builtWith:'بُني بالتعاون مع شركة',
    login:'دخول الإدارة', password:'كلمة المرور', loginButton:'دخول آمن', orders:'الطلبات', addProduct:'إضافة منتج', logout:'خروج', search:'ابحث بالاسم أو الهاتف أو رقم الطلب', filter:'تصفية', all:'الكل', new:'جديد', contacted:'تم التواصل', quoted:'تم التسعير', in_production:'قيد التجهيز', ready:'جاهز', completed:'مكتمل', cancelled:'ملغي', print:'طباعة', details:'التفاصيل', noOrders:'لا توجد طلبات مطابقة', standard:'طلب منتج', customType:'طلب خاص', update:'حفظ التحديث', priceQuote:'السعر المتفق عليه', eta:'مدة التجهيز', productSlug:'رابط المنتج', productNameAr:'الاسم بالعربية', productNameEn:'الاسم بالإنجليزية', productNameHe:'الاسم بالعبرية', price:'السعر', image:'صورة المنتج', model:'ملف GLB', saveProduct:'إضافة المنتج',
    category:'الفئة',
  },
  en: {
    home:'Home', back:'Back', products:'Products', custom:'Custom order', about:'About', contact:'Contact', admin:'Admin',
    heroEyebrow:'3D-printed automotive art', heroTitle:'Turn your passion into a one-of-one piece.', heroText:'Hand-finished 3D-printed models, personalized with your colors and text.', shopNow:'Explore collection', customCta:'Create your idea',
    categories:'Built for detail lovers', categoryText:'Pick a model, then personalize every part until it is unmistakably yours.', wheels:'Wheel models', turbo:'Turbo models', shelves:'Shelves', keychains:'Keychains', photos:'photos', catalogSearch:'Search products', noProducts:'No matching products', premium:'Premium quality', precision:'Precision printed', personalization:'Full personalization', support:'Direct support',
    collection:'Collection', collectionTitle:'Choose your next display piece', collectionText:'Real product photography with an interactive 3D preview.', viewProduct:'Customize', from:'From',
    product:'Product', customize:'Make it yours', drag:'Drag to rotate 360°', rim:'Wheel', disc:'Brake disc', caliper:'Caliper', stand:'Stand', hub:'Center hub', colors:'Colors', baseText:'Text on stand', caliperText:'Text on caliper', optional:'Optional', quantity:'Quantity', orderNow:'Send order', yourDetails:'Delivery details', name:'Full name', phone:'Phone number', code:'Country code', country:'Country', address:'Full delivery address', notes:'Notes', sending:'Sending order...', success:'Your order is in', successText:'Order number', error:'Could not send the order. Check the form or server connection.', invalidFields:'Fields to review', customerName:'Full name', countryCode:'Country code', deliveryAddress:'Delivery address', deliveryLat:'Delivery location', deliveryLng:'Delivery location',
    customTitle:'Have an original idea? Let’s print it.', customText:'Upload a clear reference, name the product and describe every part color. We will contact you with price and production time.', customName:'Product or part name', partsDescription:'Describe parts and the color of each one', upload:'Upload reference image', submitCustom:'Send custom request',
    aboutTitle:'From an idea to a piece worth displaying', aboutText:'At Revtrove, we build automotive décor layer by layer and finish every piece by hand. Every order is reviewed before production.',
    contactTitle:'Let’s talk about your project', call:'Call us', instagram:'Instagram', email:'Email', rights:'All rights reserved.', builtWith:'Built in collaboration with',
    login:'Admin sign in', password:'Password', loginButton:'Secure sign in', orders:'Orders', addProduct:'Add product', logout:'Log out', search:'Search name, phone or order number', filter:'Filter', all:'All', new:'New', contacted:'Contacted', quoted:'Quoted', in_production:'In production', ready:'Ready', completed:'Completed', cancelled:'Cancelled', print:'Print', details:'Details', noOrders:'No matching orders', standard:'Product order', customType:'Custom request', update:'Save update', priceQuote:'Quoted price', eta:'Production time', productSlug:'Product URL', productNameAr:'Arabic name', productNameEn:'English name', productNameHe:'Hebrew name', price:'Price', image:'Product image', model:'GLB model', saveProduct:'Add product',
    category:'Category',
  },
  he: {
    home:'בית', back:'חזרה', products:'מוצרים', custom:'הזמנה מיוחדת', about:'אודות', contact:'יצירת קשר', admin:'ניהול',
    heroEyebrow:'אמנות רכב בהדפסת תלת־ממד', heroTitle:'הפכו את התשוקה שלכם לפריט יחיד במינו.', heroText:'דגמים מודפסים בתלת־ממד בגימור ידני, בצבעים ובטקסט שלכם.', shopNow:'לצפייה בקולקציה', customCta:'צרו רעיון משלכם',
    categories:'נוצר לאוהבי הפרטים', categoryText:'בחרו דגם והתאימו כל חלק עד שהוא באמת שלכם.', wheels:'דגמי גלגלים', turbo:'דגמי טורבו', shelves:'מדפים', keychains:'מחזיקי מפתחות', photos:'תמונות', catalogSearch:'חיפוש מוצרים', noProducts:'לא נמצאו מוצרים מתאימים', premium:'איכות מעולה', precision:'הדפסה מדויקת', personalization:'התאמה מלאה', support:'שירות ישיר',
    collection:'קולקציה', collectionTitle:'בחרו את הפריט הבא שלכם', collectionText:'תמונות מוצר אמיתיות עם תצוגת תלת־ממד אינטראקטיבית.', viewProduct:'התאמה אישית', from:'החל מ־',
    product:'מוצר', customize:'התאימו לטעמכם', drag:'גררו לסיבוב של 360°', rim:'גלגל', disc:'דיסק בלם', caliper:'קליפר', stand:'מעמד', hub:'מרכז', colors:'צבעים', baseText:'טקסט על המעמד', caliperText:'טקסט על הקליפר', optional:'לא חובה', quantity:'כמות', orderNow:'שליחת הזמנה', yourDetails:'פרטי משלוח', name:'שם מלא', phone:'מספר טלפון', code:'קידומת מדינה', country:'מדינה', address:'כתובת משלוח מלאה', notes:'הערות', sending:'ההזמנה נשלחת...', success:'ההזמנה התקבלה', successText:'מספר הזמנה', error:'לא ניתן לשלוח את ההזמנה. בדקו את הפרטים או את החיבור לשרת.', invalidFields:'שדות לבדיקה', customerName:'שם מלא', countryCode:'קידומת מדינה', deliveryAddress:'כתובת משלוח', deliveryLat:'מיקום משלוח', deliveryLng:'מיקום משלוח',
    customTitle:'יש לכם רעיון מקורי? בואו נדפיס אותו.', customText:'העלו תמונת עזר ברורה, כתבו את שם המוצר ואת צבעי החלקים, וניצור קשר לגבי המחיר וזמן ההכנה.', customName:'שם המוצר או החלק', partsDescription:'תיאור החלקים והצבע של כל חלק', upload:'העלאת תמונת עזר', submitCustom:'שליחת בקשה מיוחדת',
    aboutTitle:'מרעיון לפריט שראוי להציג', aboutText:'ב־Revtrove אנחנו יוצרים דקורציית רכב שכבה אחר שכבה ומסיימים כל פריט בעבודת יד. כל הזמנה נבדקת לפני הייצור.',
    contactTitle:'בואו נדבר על הפרויקט שלכם', call:'טלפון', instagram:'אינסטגרם', email:'דוא״ל', rights:'כל הזכויות שמורות.', builtWith:'נבנה בשיתוף עם',
    login:'כניסת מנהל', password:'סיסמה', loginButton:'כניסה מאובטחת', orders:'הזמנות', addProduct:'הוספת מוצר', logout:'יציאה', search:'חיפוש לפי שם, טלפון או מספר הזמנה', filter:'סינון', all:'הכול', new:'חדש', contacted:'נוצר קשר', quoted:'הצעת מחיר', in_production:'בייצור', ready:'מוכן', completed:'הושלם', cancelled:'בוטל', print:'הדפסה', details:'פרטים', noOrders:'אין הזמנות תואמות', standard:'הזמנת מוצר', customType:'בקשה מיוחדת', update:'שמירת עדכון', priceQuote:'מחיר מוסכם', eta:'זמן הכנה', productSlug:'קישור המוצר', productNameAr:'שם בערבית', productNameEn:'שם באנגלית', productNameHe:'שם בעברית', price:'מחיר', image:'תמונת מוצר', model:'קובץ GLB', saveProduct:'הוספת מוצר',
    category:'קטגוריה',
  },
}

Object.assign(dictionaries.ar,{ airFilter:'فلتر الهواء', turboBody:'جسم التيربو', fan:'مروحة التيربو' })
Object.assign(dictionaries.en,{ airFilter:'Air filter', turboBody:'Turbo body', fan:'Turbo fan' })
Object.assign(dictionaries.he,{ airFilter:'מסנן אוויר', turboBody:'גוף הטורבו', fan:'מאוורר הטורבו' })

Object.assign(dictionaries.ar,{
  productDisclaimerTitle:'ملاحظة مهمة قبل الطلب', visualDisclaimer:'صور المنتجات والألوان والنصوص الظاهرة على القاعدة والكاليبر هي للتوضيح فقط، وقد تختلف النتيجة الفعلية قليلًا بحسب الشاشة والطباعة.', productionNotice:'مدة تجهيز المنتج من أسبوع إلى أسبوعين.', whatsappConfirm:'بعد إرسال الطلب سنتواصل مع الزبون عبر واتساب لتأكيد اللون والشكل والنص المطلوب قبل بدء التجهيز.', returnsNotice:'لا يمكن تبديل المنتج أو إرجاعه إلا عند وجود عطل أو كسر، أو إذا لم يطابق الشروط التي أكدها الزبون.',
  policies:'سياسة الموقع', privacy:'سياسة الخصوصية', policiesTitle:'سياسة الطلب والاستبدال', policiesIntro:'توضح هذه السياسة آلية تجهيز طلبات Revtrove وتأكيدها والاستبدال أو الإرجاع.', returnsTitle:'الاستبدال والإرجاع', returnsText:'المنتجات مخصصة حسب طلب الزبون، لذلك لا يمكن تبديلها أو إرجاعها إلا في حالات العطل أو الكسر أو عدم مطابقة اللون أو الشكل أو النص للشروط التي تم تأكيدها مع الزبون.', productionTitle:'مدة التجهيز', productionText:'يحتاج تجهيز المنتج عادةً من أسبوع إلى أسبوعين، وقد يتم إبلاغ الزبون بأي تغيير قبل بدء التنفيذ.', confirmationTitle:'تأكيد الطلب', confirmationText:'بعد استلام الطلب نتواصل مع الزبون عبر واتساب لتأكيد اللون والشكل والنص المكتوب على القاعدة أو الكاليبر قبل بدء التجهيز.', visualPolicyTitle:'الصور والمعاينة',
  privacyTitle:'سياسة الخصوصية', privacyIntro:'نحترم خصوصية زبائن Revtrove ونستخدم البيانات فقط لتنفيذ الطلب والتواصل والتوصيل.', privacyDataTitle:'البيانات التي نجمعها', privacyDataText:'قد نجمع الاسم ورقم الهاتف ورمز البلد والدولة وعنوان التوصيل والملاحظات وصور الطلبات الخاصة وتفاصيل المنتج المختار.', privacyUseTitle:'استخدام البيانات', privacyUseText:'تُستخدم البيانات لمراجعة الطلب وتأكيده عبر واتساب وتجهيز المنتج وترتيب التوصيل وتقديم الدعم.', privacySharingTitle:'مشاركة البيانات', privacySharingText:'لا نبيع بيانات الزبائن. قد تتم مشاركة الحد الأدنى اللازم فقط مع جهة التوصيل أو مزود خدمة ضروري لإتمام الطلب.', privacySecurityTitle:'حماية البيانات', privacySecurityText:'نتخذ إجراءات تقنية وتنظيمية مناسبة لحماية البيانات، مع عدم إمكانية ضمان الحماية المطلقة لأي نظام إلكتروني.', privacyContactTitle:'التواصل والطلبات', privacyContactText:'يمكن للزبون التواصل معنا لطلب تصحيح بياناته أو الاستفسار عنها عبر الهاتف أو البريد الإلكتروني الموضحين في الموقع.'
})
Object.assign(dictionaries.en,{
  productDisclaimerTitle:'Important before ordering', visualDisclaimer:'Product images, colors, and the text shown on the stand and caliper are for illustration only. The final result may vary slightly due to screens and printing.', productionNotice:'Production normally takes one to two weeks.', whatsappConfirm:'After ordering, we will contact you on WhatsApp to confirm the color, design, and requested text before production starts.', returnsNotice:'Products cannot be exchanged or returned unless defective, broken, or not made according to the confirmed requirements.',
  policies:'Store policy', privacy:'Privacy policy', policiesTitle:'Order and return policy', policiesIntro:'This policy explains how Revtrove confirms, produces, exchanges, and returns orders.', returnsTitle:'Exchanges and returns', returnsText:'Products are made to order and cannot be exchanged or returned unless defective, broken, or inconsistent with the color, design, or text confirmed with the customer.', productionTitle:'Production time', productionText:'Production normally takes one to two weeks. We will notify the customer of any expected change before work begins.', confirmationTitle:'Order confirmation', confirmationText:'After receiving an order, we contact the customer on WhatsApp to confirm the color, design, and text on the stand or caliper before production.', visualPolicyTitle:'Images and previews',
  privacyTitle:'Privacy policy', privacyIntro:'We respect Revtrove customers’ privacy and use personal information only to process orders, communicate, and arrange delivery.', privacyDataTitle:'Information we collect', privacyDataText:'We may collect name, phone number, country code, country, delivery address, notes, custom-order images, and selected product details.', privacyUseTitle:'How we use information', privacyUseText:'Information is used to review and confirm orders through WhatsApp, produce products, arrange delivery, and provide support.', privacySharingTitle:'Information sharing', privacySharingText:'We do not sell customer data. We may share only the minimum necessary information with delivery providers or essential service providers.', privacySecurityTitle:'Data security', privacySecurityText:'We use reasonable technical and organizational measures to protect information, although no electronic system can guarantee absolute security.', privacyContactTitle:'Contact and requests', privacyContactText:'Customers may contact us using the phone number or email on this site to ask about or correct their information.'
})
Object.assign(dictionaries.he,{
  productDisclaimerTitle:'חשוב לפני ההזמנה', visualDisclaimer:'תמונות המוצרים, הצבעים והטקסט המוצג על המעמד והקליפר הם להמחשה בלבד. התוצאה בפועל עשויה להשתנות מעט בהתאם למסך ולהדפסה.', productionNotice:'זמן ההכנה הוא בדרך כלל בין שבוע לשבועיים.', whatsappConfirm:'לאחר ההזמנה ניצור קשר בוואטסאפ לאישור הצבע, העיצוב והטקסט לפני תחילת הייצור.', returnsNotice:'לא ניתן להחליף או להחזיר מוצר אלא במקרה של פגם, שבר או אי־התאמה לדרישות שאושרו.',
  policies:'מדיניות האתר', privacy:'מדיניות פרטיות', policiesTitle:'מדיניות הזמנות והחזרות', policiesIntro:'מדיניות זו מסבירה כיצד Revtrove מאשרת, מייצרת, מחליפה ומחזירה הזמנות.', returnsTitle:'החלפות והחזרות', returnsText:'המוצרים מיוצרים לפי הזמנה ולכן לא ניתן להחליפם או להחזירם אלא במקרה של פגם, שבר או אי־התאמה לצבע, לעיצוב או לטקסט שאושרו עם הלקוח.', productionTitle:'זמן הכנה', productionText:'זמן ההכנה הוא בדרך כלל בין שבוע לשבועיים. כל שינוי צפוי יימסר ללקוח לפני תחילת העבודה.', confirmationTitle:'אישור ההזמנה', confirmationText:'לאחר קבלת ההזמנה ניצור קשר עם הלקוח בוואטסאפ כדי לאשר את הצבע, העיצוב והטקסט על המעמד או הקליפר.', visualPolicyTitle:'תמונות והדמיות',
  privacyTitle:'מדיניות פרטיות', privacyIntro:'אנו מכבדים את פרטיות לקוחות Revtrove ומשתמשים במידע רק לצורך ביצוע ההזמנה, תקשורת ומשלוח.', privacyDataTitle:'המידע שאנו אוספים', privacyDataText:'אנו עשויים לאסוף שם, מספר טלפון, קידומת מדינה, מדינה, כתובת משלוח, הערות, תמונות להזמנה מיוחדת ופרטי המוצר שנבחר.', privacyUseTitle:'שימוש במידע', privacyUseText:'המידע משמש לבדיקת ההזמנה ואישורה בוואטסאפ, לייצור המוצר, לתיאום משלוח ולמתן תמיכה.', privacySharingTitle:'שיתוף מידע', privacySharingText:'איננו מוכרים מידע של לקוחות. ניתן לשתף רק את המידע המינימלי הנדרש עם שירות המשלוחים או ספק שירות חיוני.', privacySecurityTitle:'אבטחת מידע', privacySecurityText:'אנו נוקטים אמצעים טכניים וארגוניים סבירים להגנת המידע, אך אין מערכת אלקטרונית שמבטיחה אבטחה מוחלטת.', privacyContactTitle:'יצירת קשר ובקשות', privacyContactText:'ניתן לפנות אלינו בטלפון או בדוא״ל המופיעים באתר כדי לברר או לתקן מידע אישי.'
})

Object.assign(dictionaries.ar,{ discoverDetails:'اكتشف التفاصيل', contactTitle:'خلّي خيالك يصير حقيقة 😉😎' })
Object.assign(dictionaries.en,{ discoverDetails:'Discover details', contactTitle:'Turn your imagination into reality 😉😎' })
Object.assign(dictionaries.he,{ discoverDetails:'גלו את הפרטים', contactTitle:'הפכו את הדמיון למציאות 😉😎' })

Object.assign(dictionaries.ar,{
  deliveryLocation:'موقع التوصيل', deliveryLocationHelp:'استخدم موقعك الحالي أو ابحث عن عنوان آخر، ثم حرّك الدبوس لتحديد المكان بدقة.', useMyLocation:'استخدم موقعي الحالي', locating:'جارٍ تحديد موقعك...', searchAddress:'ابحث عن المنطقة أو الشارع', confirmedAddress:'العنوان المؤكد', manualAddress:'اكتب اسم المنطقة والشارع والحارة', deliveryPin:'موقع التوصيل الدقيق', mapsNeedsKey:'أدخل العنوان يدويًا. تحتاج الخريطة إلى إعداد مفتاح Google Maps.', locationDenied:'تعذر الوصول إلى موقعك. اسمح بالوصول أو اختر العنوان يدويًا.', locationUnsupported:'تحديد الموقع غير مدعوم في هذا الجهاز.', geocodeError:'تم تحديد الدبوس، لكن تعذر قراءة اسم العنوان. يمكنك كتابته يدويًا.', pinConfirmed:'تم تحديد الموقع. يمكنك سحب الدبوس لمزيد من الدقة.', pinInstruction:'ابحث عن عنوان أو اضغط على الخريطة لوضع الدبوس.', openExactLocation:'فتح الموقع الدقيق في Google Maps'
})
Object.assign(dictionaries.en,{
  deliveryLocation:'Delivery location', deliveryLocationHelp:'Use your current location or search for another address, then drag the pin for precision.', useMyLocation:'Use my current location', locating:'Locating...', searchAddress:'Search area or street', confirmedAddress:'Confirmed address', manualAddress:'Enter area, street, and neighborhood', deliveryPin:'Exact delivery location', mapsNeedsKey:'Enter the address manually. The map requires a Google Maps API key.', locationDenied:'We could not access your location. Allow access or choose the address manually.', locationUnsupported:'Location is not supported on this device.', geocodeError:'The pin was set, but the address name could not be found. You can enter it manually.', pinConfirmed:'Location selected. Drag the pin for more precision.', pinInstruction:'Search for an address or click the map to place the pin.', openExactLocation:'Open exact location in Google Maps'
})
Object.assign(dictionaries.he,{
  deliveryLocation:'מיקום למשלוח', deliveryLocationHelp:'השתמשו במיקום הנוכחי או חפשו כתובת אחרת, ולאחר מכן גררו את הסיכה לדיוק.', useMyLocation:'השתמשו במיקום שלי', locating:'מאתר מיקום...', searchAddress:'חיפוש אזור או רחוב', confirmedAddress:'כתובת מאושרת', manualAddress:'הזינו אזור, רחוב ושכונה', deliveryPin:'מיקום מדויק למשלוח', mapsNeedsKey:'הזינו את הכתובת ידנית. המפה דורשת מפתח Google Maps.', locationDenied:'לא ניתן לגשת למיקום. אשרו גישה או בחרו כתובת ידנית.', locationUnsupported:'שירות המיקום אינו נתמך במכשיר זה.', geocodeError:'הסיכה נקבעה אך לא נמצא שם הכתובת. ניתן להזין אותה ידנית.', pinConfirmed:'המיקום נבחר. גררו את הסיכה לדיוק נוסף.', pinInstruction:'חפשו כתובת או לחצו על המפה כדי להציב סיכה.', openExactLocation:'פתיחת המיקום המדויק ב-Google Maps'
})

Object.assign(dictionaries.ar,{ productPhotos:'صور المنتج', view360:'عرض 360°', photo:'صورة' })
Object.assign(dictionaries.en,{ productPhotos:'Product photos', view360:'360° view', photo:'Photo' })
Object.assign(dictionaries.he,{ productPhotos:'תמונות המוצר', view360:'תצוגת 360°', photo:'תמונה' })

Object.assign(dictionaries.ar,{ addressLookup:'جارٍ قراءة اسم المنطقة والعنوان...', fallbackLocationConfirmed:'تم تحديد موقعك وعرضه على الخريطة. يمكنك فتح Google Maps أو تعديل العنوان.', openInMaps:'فتح الخريطة', locationProvider:'يتم تحديد اسم المنطقة من إحداثيات موقعك الحالي عبر BigDataCloud عند تعذر Google Maps.' })
Object.assign(dictionaries.en,{ addressLookup:'Reading the area and address...', fallbackLocationConfirmed:'Your location is selected and shown on the map. You can open Google Maps or edit the address.', openInMaps:'Open map', locationProvider:'When Google Maps is unavailable, the area name is resolved from your current coordinates using BigDataCloud.' })
Object.assign(dictionaries.he,{ addressLookup:'קורא את שם האזור והכתובת...', fallbackLocationConfirmed:'המיקום נבחר ומוצג במפה. ניתן לפתוח את Google Maps או לערוך את הכתובת.', openInMaps:'פתיחת המפה', locationProvider:'כאשר Google Maps אינו זמין, שם האזור מזוהה מקואורדינטות המיקום הנוכחי באמצעות BigDataCloud.' })

Object.assign(dictionaries.ar,{ mapsNeedsKey:'اضغط «استخدم موقعي الحالي» لفتح خريطة تفاعلية، أو اكتب العنوان يدوياً.', fallbackLocationConfirmed:'تم تحديد الموقع. اسحب الدبوس أو اضغط على الخريطة لتغييره بدقة.', locationProvider:'الخريطة والعنوان مقدمان عبر OpenStreetMap عند تعذر Google Maps.' })
Object.assign(dictionaries.en,{ mapsNeedsKey:'Select “Use my current location” to open an interactive map, or enter the address manually.', fallbackLocationConfirmed:'Location selected. Drag the pin or click the map to adjust it precisely.', locationProvider:'Map and address data are provided by OpenStreetMap when Google Maps is unavailable.' })
Object.assign(dictionaries.he,{ mapsNeedsKey:'בחרו „השתמשו במיקום שלי” כדי לפתוח מפה אינטראקטיבית, או הזינו כתובת ידנית.', fallbackLocationConfirmed:'המיקום נבחר. גררו את הסיכה או לחצו על המפה כדי לדייק.', locationProvider:'המפה ופרטי הכתובת מסופקים על ידי OpenStreetMap כאשר Google Maps אינו זמין.' })

export const rtlLanguages = new Set(['ar', 'he'])
