import {useState} from 'react'
import {askConfirmation} from './lib/site-dialogs'
import {requiresColor} from '../../shared/product-configuration.mjs'
import './details.css'
export default function ProductDetails({fields,options,setOptions,product}){
 const [adding,setAdding]=useState(null)
 const palette=product.colors||[]
 const assign=(field,color)=>{const old=options[field.key]||{},colors=(old.colors||[]).filter(c=>palette.some(x=>x.hex.toLowerCase()===c.hex.toLowerCase())&&(!Array.isArray(field.allowed_colors)||field.allowed_colors.some(x=>x.hex.toLowerCase()===c.hex.toLowerCase())));setOptions({...options,[field.key]:{...old,defaultColor:null,colors:[...colors.filter(c=>c.hex!==color.hex),color]}});setAdding(null)}
 return <section className="product-details-readonly"><h3>تفصيلات الفئة</h3>{!fields.length&&<small>لا توجد تفصيلات لهذه الفئة.</small>}{fields.map(field=>{const allowed=palette.filter(c=>!Array.isArray(field.allowed_colors)||field.allowed_colors.some(x=>x.hex.toLowerCase()===c.hex.toLowerCase())),selected=(options[field.key]?.colors||[]).filter(c=>allowed.some(x=>x.hex.toLowerCase()===c.hex.toLowerCase()));return <div className="product-detail-line" key={field.key}><strong>{field.label_ar}</strong>{requiresColor(field)&&<><div className="detail-color-tags">{selected.map(c=><button type="button" key={c.hex} title="إزالة اللون" onClick={async()=>{if(await askConfirmation('إزالة اللون من التفصيل؟ '+c.name_ar))setOptions({...options,[field.key]:{...options[field.key],defaultColor:null,colors:selected.filter(x=>x.hex!==c.hex)}})}}><i style={{background:c.hex}}/>{c.name_ar} ×</button>)}</div><button type="button" className="button outline" onClick={()=>setAdding(adding===field.key?null:field.key)}>إضافة لون</button>{adding===field.key&&<select aria-label={'إضافة لون — '+field.label_ar} value="" onChange={e=>{const color=allowed.find(c=>c.hex===e.target.value);if(color)assign(field,color)}}><option value="">اختر لونًا</option>{allowed.filter(c=>!selected.some(x=>x.hex===c.hex)).map(c=><option value={c.hex} key={c.hex}>{c.name_ar}</option>)}</select>}{adding===field.key&&!allowed.length&&<small>لا توجد ألوان مرتبطة بهذا المنتج ومسموحة لهذا التفصيل. أضفها من صفحتي الألوان والتفصيلات.</small>}</>}</div>})}<small>تُعرض تفاصيل الفئة تلقائيًا للزبون بلغته. لا يمكن تعديل التفصيل هنا.</small></section>
}
